# Training Data Penuh

Catatan: notebook ini adalah training awal di RTX 5060 Ti dan sekarang disimpan sebagai arsip. Semua training final (pencarian learning rate, seed 43 dan 44, dan uji layer yang dibekukan) dijalankan ulang di RTX 5070 Ti pada notebook 06, dan hasil test ada di notebook 07. Angka di notebook ini tidak dipakai di paper.

Notebook ini melatih RoBERTa (`roberta-base`) dan DistilBERT (`distilbert-base-cased`) dengan seluruh data latih, yaitu 799.459 pasangan parent dan comment. Setiap model dinilai di 100.276 data validasi.

Ada 3 jenis input yang dibandingkan:
- comment saja, model hanya membaca comment,
- early fusion, parent dan comment digabung menjadi satu input,
- late fusion, parent dan comment dibaca terpisah lalu hasilnya digabung.

Selain membandingkan model dan jenis input, notebook ini juga melihat pengaruh learning rate. Learning rate adalah seberapa besar model mengubah dirinya setiap kali belajar dari satu batch data. Nilai yang dicoba adalah 1e-5, 2e-5, 3e-5, dan 5e-5.

Pengaturan yang sama untuk semua run:

| Pengaturan | Nilai |
|---|---|
| Panjang maksimal input | 256 token |
| Batch size | 32 |
| Epoch | 3 |
| Warmup | 10% langkah pertama |
| Weight decay | 0,01 |
| Optimizer | AdamW |
| Presisi | BF16 |
| Seed | 42 |
| Pemilihan epoch terbaik | macro-F1 validasi |

Data test tidak dilihat di notebook ini. Prediksi data test disimpan terpisah di folder `test_sealed/` dan baru dibuka setelah konfigurasi final dipilih.

## 1. Setup

Kode training yang sama dengan `04_pilot` dipanggil dari `src/training.py`. Hasil disimpan ke folder `data/training_rtx5060ti/full/`.

In [1]:
import sys, importlib
from pathlib import Path

import pandas as pd
import torch
import transformers

ROOT = Path.cwd().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import training as T
importlib.reload(T)
transformers.logging.set_verbosity_error()

DATA_DIR = ROOT / "data/tokenized_full"
OUT_DIR = ROOT / "data/training_rtx5060ti/full"
PUTARAN = [1, 2, 3]

free, total = torch.cuda.mem_get_info()
print("GPU:", torch.cuda.get_device_name(), f"| VRAM terpakai {(total - free) / 1e9:.1f} / {total / 1e9:.1f} GB")
print("Pemilihan epoch terbaik:", T.DEFAULTS["select_metric"])

d:\Falah\TA\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

GPU: NVIDIA GeForce RTX 5060 Ti | VRAM terpakai 1.2 / 17.1 GB
Pemilihan epoch terbaik: macro_f1

#### Insight
GPU yang dipakai NVIDIA GeForce RTX 5060 Ti, dan sebelum training memorinya baru terpakai 1,2 GB untuk tampilan layar. Epoch terbaik dipilih memakai macro-F1, yaitu rata-rata F1 kelas sarkas dan kelas bukan sarkas, supaya model yang terlalu sering menebak "sarkas" tidak ikut terpilih.

## 2. Daftar Run

Run dibagi menjadi tiga putaran supaya hasil yang paling penting selesai lebih dulu:

| Putaran | Isi | Jumlah run |
|---|---|---:|
| 1 | 3 input × 2 model, learning rate 3e-5 | 6 |
| 2 | early fusion × 2 model, learning rate 1e-5, 2e-5, 5e-5 | 6 |
| 3 | comment saja dan late fusion × 2 model, learning rate 1e-5, 2e-5, 5e-5 | 12 |

Setelah ketiga putaran selesai, setiap kombinasi input dan model punya hasil untuk keempat learning rate.

In [2]:
queue = T.build_queue(PUTARAN)
T.run_status(queue, OUT_DIR)

,run_id,round,input,model,lr,seed,status
0,R1_comment_roberta_lr3e-05_s42,1,comment,roberta,0.00003,42,belum
1,R1_comment_distilbert_lr3e-05_s42,1,comment,distilbert,0.00003,42,belum
2,R1_early_roberta_lr3e-05_s42,1,early,roberta,0.00003,42,belum
3,R1_early_distilbert_lr3e-05_s42,1,early,distilbert,0.00003,42,belum
4,R1_late_roberta_lr3e-05_s42,1,late,roberta,0.00003,42,belum
5,R1_late_distilbert_lr3e-05_s42,1,late,distilbert,0.00003,42,belum
6,R2_early_roberta_lr1e-05_s42,2,early,roberta,0.00001,42,belum
7,R2_early_distilbert_lr1e-05_s42,2,early,distilbert,0.00001,42,belum
8,R2_early_roberta_lr2e-05_s42,2,early,roberta,0.00002,42,belum
9,R2_early_distilbert_lr2e-05_s42,2,early,distilbert,0.00002,42,belum
10,R2_early_roberta_lr5e-05_s42,2,early,roberta,0.00005,42,belum
11,R2_early_distilbert_lr5e-05_s42,2,early,distilbert,0.00005,42,belum
12,R3_comment_roberta_lr1e-05_s42,3,comment,roberta,0.00001,42,belum
13,R3_comment_distilbert_lr1e-05_s42,3,comment,distilbert,0.00001,42,belum
14,R3_comment_roberta_lr2e-05_s42,3,comment,roberta,0.00002,42,belum
15,R3_comment_distilbert_lr2e-05_s42,3,comment,distilbert,0.00002,42,belum
16,R3_comment_roberta_lr5e-05_s42,3,comment,roberta,0.00005,42,belum
17,R3_comment_distilbert_lr5e-05_s42,3,comment,distilbert,0.00005,42,belum
18,R3_late_roberta_lr1e-05_s42,3,late,roberta,0.00001,42,belum
19,R3_late_distilbert_lr1e-05_s42,3,late,distilbert,0.00001,42,belum
20,R3_late_roberta_lr2e-05_s42,3,late,roberta,0.00002,42,belum
21,R3_late_distilbert_lr2e-05_s42,3,late,distilbert,0.00002,42,belum
22,R3_late_roberta_lr5e-05_s42,3,late,roberta,0.00005,42,belum
23,R3_late_distilbert_lr5e-05_s42,3,late,distilbert,0.00005,42,belum

#### Insight
Ada 24 run dan semuanya masih berstatus "belum" saat training dimulai, jadi folder hasil masih kosong.

## 3. Training

Run dijalankan satu per satu. Di setiap epoch, model belajar dari seluruh data latih, lalu dinilai di data validasi. Setiap 10% epoch, loss dan learning rate dicatat ke `train_log.csv`. Setelah 3 epoch, model dari epoch dengan macro-F1 terbaik dipakai untuk menebak data test dan diukur kecepatannya.

Kalau training terputus, sel ini cukup dijalankan ulang. Run yang sudah selesai dilewati, dan run yang terputus dilanjutkan dari epoch terakhir yang sudah selesai.

In [3]:
for cfg in queue:
    T.run_experiment(cfg, DATA_DIR, OUT_DIR)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 527.61it/s]

[R1_comment_roberta_lr3e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6010 | lr 1.00e-05 | 3.1 mnt, sisa ±27.5 mnt
  epoch 1 |  4,997/24,984 | loss 0.5378 | lr 2.00e-05 | 6.1 mnt, sisa ±24.3 mnt
  epoch 1 |  7,496/24,984 | loss 0.5318 | lr 3.00e-05 | 9.1 mnt, sisa ±21.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5199 | lr 2.89e-05 | 12.1 mnt, sisa ±18.1 mnt
  epoch 1 | 12,492/24,984 | loss 0.5114 | lr 2.78e-05 | 15.1 mnt, sisa ±15.1 mnt
  epoch 1 | 14,991/24,984 | loss 0.5051 | lr 2.67e-05 | 18.1 mnt, sisa ±12.1 mnt
  epoch 1 | 17,489/24,984 | loss 0.5007 | lr 2.56e-05 | 21.2 mnt, sisa ±9.1 mnt
  epoch 1 | 19,988/24,984 | loss 0.4949 | lr 2.44e-05 | 24.2 mnt, sisa ±6.1 mnt
  epoch 1 | 22,486/24,984 | loss 0.4902 | lr 2.33e-05 | 27.3 mnt, sisa ±3.0 mnt
  epoch 1 | 24,984/24,984 | loss 0.4899 | lr 2.22e-05 | 30.3 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 30.3 mnt | val loss 0.4779 | acc 0.7724 P 0.7948 R 0.7267 F1 0.7593 macro-F1 0.7717
  epoch 2 |  2,499/24,984 | loss 0.4536 | lr 2.11e-05 | 3.1 mnt, sisa ±27.4 mnt
  epoch 2 |  4,997/24,984 | loss 0.4503 | lr 2.00e-05 | 6.1 mnt, sisa ±24.4 mnt
  epoch 2 |  7,496/24,984 | loss 0.4520 | lr 1.89e-05 | 9.1 mnt, sisa ±21.3 mnt
  epoch 2 |  9,994/24,984 | loss 0.4536 | lr 1.78e-05 | 12.2 mnt, sisa ±18.2 mnt
  epoch 2 | 12,492/24,984 | loss 0.4504 | lr 1.67e-05 | 15.2 mnt, sisa ±15.2 mnt
  epoch 2 | 14,991/24,984 | loss 0.4504 | lr 1.56e-05 | 18.3 mnt, sisa ±12.2 mnt
  epoch 2 | 17,489/24,984 | loss 0.4486 | lr 1.44e-05 | 21.3 mnt, sisa ±9.1 mnt
  epoch 2 | 19,988/24,984 | loss 0.4491 | lr 1.33e-05 | 24.4 mnt, sisa ±6.1 mnt
  epoch 2 | 22,486/24,984 | loss 0.4410 | lr 1.22e-05 | 27.4 mnt, sisa ±3.0 mnt
  epoch 2 | 24,984/24,984 | loss 0.4440 | lr 1.11e-05 | 30.5 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 30.5 mnt | val loss 0.4708 | acc 0.7792 P 0.7749 R 0.7792 F1 0.7771 macro-F1 0.7792
  epoch 3 |  2,499/24,984 | loss 0.3950 | lr 1.00e-05 | 3.1 mnt, sisa ±28.2 mnt
  epoch 3 |  4,997/24,984 | loss 0.3971 | lr 8.89e-06 | 6.3 mnt, sisa ±25.4 mnt
  epoch 3 |  7,496/24,984 | loss 0.3932 | lr 7.78e-06 | 9.5 mnt, sisa ±22.2 mnt
  epoch 3 |  9,994/24,984 | loss 0.3891 | lr 6.67e-06 | 12.6 mnt, sisa ±18.9 mnt
  epoch 3 | 12,492/24,984 | loss 0.3941 | lr 5.56e-06 | 15.7 mnt, sisa ±15.7 mnt
  epoch 3 | 14,991/24,984 | loss 0.3919 | lr 4.44e-06 | 18.8 mnt, sisa ±12.5 mnt
  epoch 3 | 17,489/24,984 | loss 0.3874 | lr 3.33e-06 | 21.9 mnt, sisa ±9.4 mnt
  epoch 3 | 19,988/24,984 | loss 0.3883 | lr 2.22e-06 | 25.0 mnt, sisa ±6.3 mnt
  epoch 3 | 22,486/24,984 | loss 0.3850 | lr 1.11e-06 | 28.1 mnt, sisa ±3.1 mnt
  epoch 3 | 24,984/24,984 | loss 0.3853 | lr 0.00e+00 | 31.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 31.2 mnt | val loss 0.4923 | acc 0.7808 P 0.7772 R 0.7796 F1 0.7784 macro-F1 0.7808
[R1_comment_roberta_lr3e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7808 | training 92.1 mnt | memori puncak 5.08 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 987.08it/s]

[R1_comment_distilbert_lr3e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6103 | lr 1.00e-05 | 1.6 mnt, sisa ±14.5 mnt
  epoch 1 |  4,997/24,984 | loss 0.5517 | lr 2.00e-05 | 3.2 mnt, sisa ±12.9 mnt
  epoch 1 |  7,496/24,984 | loss 0.5367 | lr 3.00e-05 | 4.8 mnt, sisa ±11.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5245 | lr 2.89e-05 | 6.4 mnt, sisa ±9.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5139 | lr 2.78e-05 | 8.0 mnt, sisa ±8.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.5133 | lr 2.67e-05 | 9.6 mnt, sisa ±6.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.5057 | lr 2.56e-05 | 11.2 mnt, sisa ±4.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.5003 | lr 2.44e-05 | 12.8 mnt, sisa ±3.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.4980 | lr 2.33e-05 | 14.4 mnt, sisa ±1.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4968 | lr 2.22e-05 | 16.0 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 16.0 mnt | val loss 0.5032 | acc 0.7579 P 0.7489 R 0.7670 F1 0.7578 macro-F1 0.7579
  epoch 2 |  2,499/24,984 | loss 0.4545 | lr 2.11e-05 | 1.6 mnt, sisa ±14.4 mnt
  epoch 2 |  4,997/24,984 | loss 0.4490 | lr 2.00e-05 | 3.2 mnt, sisa ±12.8 mnt
  epoch 2 |  7,496/24,984 | loss 0.4506 | lr 1.89e-05 | 4.8 mnt, sisa ±11.2 mnt
  epoch 2 |  9,994/24,984 | loss 0.4533 | lr 1.78e-05 | 6.4 mnt, sisa ±9.5 mnt
  epoch 2 | 12,492/24,984 | loss 0.4478 | lr 1.67e-05 | 8.0 mnt, sisa ±8.0 mnt
  epoch 2 | 14,991/24,984 | loss 0.4492 | lr 1.56e-05 | 9.6 mnt, sisa ±6.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4486 | lr 1.44e-05 | 11.2 mnt, sisa ±4.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4483 | lr 1.33e-05 | 12.7 mnt, sisa ±3.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4440 | lr 1.22e-05 | 14.3 mnt, sisa ±1.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4443 | lr 1.11e-05 | 15.9 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 15.9 mnt | val loss 0.4889 | acc 0.7669 P 0.7760 R 0.7423 F1 0.7588 macro-F1 0.7667
  epoch 3 |  2,499/24,984 | loss 0.3781 | lr 1.00e-05 | 1.7 mnt, sisa ±15.0 mnt
  epoch 3 |  4,997/24,984 | loss 0.3747 | lr 8.89e-06 | 3.3 mnt, sisa ±13.3 mnt
  epoch 3 |  7,496/24,984 | loss 0.3753 | lr 7.78e-06 | 5.0 mnt, sisa ±11.6 mnt
  epoch 3 |  9,994/24,984 | loss 0.3691 | lr 6.67e-06 | 6.6 mnt, sisa ±9.8 mnt
  epoch 3 | 12,492/24,984 | loss 0.3706 | lr 5.56e-06 | 8.2 mnt, sisa ±8.2 mnt
  epoch 3 | 14,991/24,984 | loss 0.3679 | lr 4.44e-06 | 9.8 mnt, sisa ±6.5 mnt
  epoch 3 | 17,489/24,984 | loss 0.3699 | lr 3.33e-06 | 11.4 mnt, sisa ±4.9 mnt
  epoch 3 | 19,988/24,984 | loss 0.3714 | lr 2.22e-06 | 13.0 mnt, sisa ±3.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.3688 | lr 1.11e-06 | 14.6 mnt, sisa ±1.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.3624 | lr 0.00e+00 | 16.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 16.2 mnt | val loss 0.5262 | acc 0.7637 P 0.7610 R 0.7603 F1 0.7606 macro-F1 0.7637
[R1_comment_distilbert_lr3e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7667 | training 48.1 mnt | memori puncak 2.63 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 516.67it/s]

[R1_early_roberta_lr3e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.5991 | lr 1.00e-05 | 3.3 mnt, sisa ±30.1 mnt
  epoch 1 |  4,997/24,984 | loss 0.5305 | lr 2.00e-05 | 6.7 mnt, sisa ±26.6 mnt
  epoch 1 |  7,496/24,984 | loss 0.5180 | lr 3.00e-05 | 10.0 mnt, sisa ±23.3 mnt
  epoch 1 |  9,994/24,984 | loss 0.5103 | lr 2.89e-05 | 13.3 mnt, sisa ±20.0 mnt
  epoch 1 | 12,492/24,984 | loss 0.4978 | lr 2.78e-05 | 16.7 mnt, sisa ±16.7 mnt
  epoch 1 | 14,991/24,984 | loss 0.4879 | lr 2.67e-05 | 20.1 mnt, sisa ±13.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.4867 | lr 2.56e-05 | 23.5 mnt, sisa ±10.1 mnt
  epoch 1 | 19,988/24,984 | loss 0.4810 | lr 2.44e-05 | 26.9 mnt, sisa ±6.7 mnt
  epoch 1 | 22,486/24,984 | loss 0.4742 | lr 2.33e-05 | 30.2 mnt, sisa ±3.4 mnt
  epoch 1 | 24,984/24,984 | loss 0.4742 | lr 2.22e-05 | 33.5 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 33.5 mnt | val loss 0.4607 | acc 0.7816 P 0.7712 R 0.7929 F1 0.7819 macro-F1 0.7816
  epoch 2 |  2,499/24,984 | loss 0.4308 | lr 2.11e-05 | 3.4 mnt, sisa ±30.7 mnt
  epoch 2 |  4,997/24,984 | loss 0.4323 | lr 2.00e-05 | 6.7 mnt, sisa ±27.0 mnt
  epoch 2 |  7,496/24,984 | loss 0.4311 | lr 1.89e-05 | 10.1 mnt, sisa ±23.5 mnt
  epoch 2 |  9,994/24,984 | loss 0.4288 | lr 1.78e-05 | 13.4 mnt, sisa ±20.1 mnt
  epoch 2 | 12,492/24,984 | loss 0.4270 | lr 1.67e-05 | 16.7 mnt, sisa ±16.7 mnt
  epoch 2 | 14,991/24,984 | loss 0.4241 | lr 1.56e-05 | 20.1 mnt, sisa ±13.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4280 | lr 1.44e-05 | 23.4 mnt, sisa ±10.0 mnt
  epoch 2 | 19,988/24,984 | loss 0.4232 | lr 1.33e-05 | 26.7 mnt, sisa ±6.7 mnt
  epoch 2 | 22,486/24,984 | loss 0.4187 | lr 1.22e-05 | 30.0 mnt, sisa ±3.3 mnt
  epoch 2 | 24,984/24,984 | loss 0.4200 | lr 1.11e-05 | 33.3 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 33.3 mnt | val loss 0.4599 | acc 0.7927 P 0.7994 R 0.7747 F1 0.7868 macro-F1 0.7926
  epoch 3 |  2,499/24,984 | loss 0.3647 | lr 1.00e-05 | 3.3 mnt, sisa ±30.1 mnt
  epoch 3 |  4,997/24,984 | loss 0.3571 | lr 8.89e-06 | 6.7 mnt, sisa ±26.6 mnt
  epoch 3 |  7,496/24,984 | loss 0.3577 | lr 7.78e-06 | 10.0 mnt, sisa ±23.3 mnt
  epoch 3 |  9,994/24,984 | loss 0.3567 | lr 6.67e-06 | 13.3 mnt, sisa ±20.0 mnt
  epoch 3 | 12,492/24,984 | loss 0.3528 | lr 5.56e-06 | 16.7 mnt, sisa ±16.7 mnt
  epoch 3 | 14,991/24,984 | loss 0.3565 | lr 4.44e-06 | 20.0 mnt, sisa ±13.3 mnt
  epoch 3 | 17,489/24,984 | loss 0.3515 | lr 3.33e-06 | 23.3 mnt, sisa ±10.0 mnt
  epoch 3 | 19,988/24,984 | loss 0.3512 | lr 2.22e-06 | 26.6 mnt, sisa ±6.7 mnt
  epoch 3 | 22,486/24,984 | loss 0.3529 | lr 1.11e-06 | 29.9 mnt, sisa ±3.3 mnt
  epoch 3 | 24,984/24,984 | loss 0.3503 | lr 0.00e+00 | 33.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 33.2 mnt | val loss 0.4770 | acc 0.7924 P 0.7796 R 0.8080 F1 0.7936 macro-F1 0.7924
[R1_early_roberta_lr3e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7926 | training 100.1 mnt | memori puncak 5.11 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 969.48it/s]

[R1_early_distilbert_lr3e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6188 | lr 1.00e-05 | 1.8 mnt, sisa ±16.1 mnt
  epoch 1 |  4,997/24,984 | loss 0.5536 | lr 2.00e-05 | 3.6 mnt, sisa ±14.5 mnt
  epoch 1 |  7,496/24,984 | loss 0.5353 | lr 3.00e-05 | 5.4 mnt, sisa ±12.7 mnt
  epoch 1 |  9,994/24,984 | loss 0.5257 | lr 2.89e-05 | 7.3 mnt, sisa ±10.9 mnt
  epoch 1 | 12,492/24,984 | loss 0.5119 | lr 2.78e-05 | 9.1 mnt, sisa ±9.1 mnt
  epoch 1 | 14,991/24,984 | loss 0.5054 | lr 2.67e-05 | 10.8 mnt, sisa ±7.2 mnt
  epoch 1 | 17,489/24,984 | loss 0.4997 | lr 2.56e-05 | 12.6 mnt, sisa ±5.4 mnt
  epoch 1 | 19,988/24,984 | loss 0.4980 | lr 2.44e-05 | 14.3 mnt, sisa ±3.6 mnt
  epoch 1 | 22,486/24,984 | loss 0.4937 | lr 2.33e-05 | 16.0 mnt, sisa ±1.8 mnt
  epoch 1 | 24,984/24,984 | loss 0.4914 | lr 2.22e-05 | 17.8 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 17.8 mnt | val loss 0.4829 | acc 0.7672 P 0.7858 R 0.7266 F1 0.7550 macro-F1 0.7666
  epoch 2 |  2,499/24,984 | loss 0.4406 | lr 2.11e-05 | 1.7 mnt, sisa ±15.7 mnt
  epoch 2 |  4,997/24,984 | loss 0.4382 | lr 2.00e-05 | 3.5 mnt, sisa ±13.9 mnt
  epoch 2 |  7,496/24,984 | loss 0.4415 | lr 1.89e-05 | 5.2 mnt, sisa ±12.2 mnt
  epoch 2 |  9,994/24,984 | loss 0.4399 | lr 1.78e-05 | 6.9 mnt, sisa ±10.4 mnt
  epoch 2 | 12,492/24,984 | loss 0.4354 | lr 1.67e-05 | 8.7 mnt, sisa ±8.7 mnt
  epoch 2 | 14,991/24,984 | loss 0.4355 | lr 1.56e-05 | 10.4 mnt, sisa ±6.9 mnt
  epoch 2 | 17,489/24,984 | loss 0.4342 | lr 1.44e-05 | 12.2 mnt, sisa ±5.2 mnt
  epoch 2 | 19,988/24,984 | loss 0.4353 | lr 1.33e-05 | 14.0 mnt, sisa ±3.5 mnt
  epoch 2 | 22,486/24,984 | loss 0.4296 | lr 1.22e-05 | 15.7 mnt, sisa ±1.7 mnt
  epoch 2 | 24,984/24,984 | loss 0.4330 | lr 1.11e-05 | 17.4 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 17.4 mnt | val loss 0.4742 | acc 0.7742 P 0.7654 R 0.7825 F1 0.7738 macro-F1 0.7742
  epoch 3 |  2,499/24,984 | loss 0.3532 | lr 1.00e-05 | 1.7 mnt, sisa ±15.6 mnt
  epoch 3 |  4,997/24,984 | loss 0.3529 | lr 8.89e-06 | 3.5 mnt, sisa ±13.9 mnt
  epoch 3 |  7,496/24,984 | loss 0.3499 | lr 7.78e-06 | 5.2 mnt, sisa ±12.1 mnt
  epoch 3 |  9,994/24,984 | loss 0.3479 | lr 6.67e-06 | 6.9 mnt, sisa ±10.4 mnt
  epoch 3 | 12,492/24,984 | loss 0.3459 | lr 5.56e-06 | 8.7 mnt, sisa ±8.7 mnt
  epoch 3 | 14,991/24,984 | loss 0.3466 | lr 4.44e-06 | 10.4 mnt, sisa ±6.9 mnt
  epoch 3 | 17,489/24,984 | loss 0.3476 | lr 3.33e-06 | 12.1 mnt, sisa ±5.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.3467 | lr 2.22e-06 | 13.9 mnt, sisa ±3.5 mnt
  epoch 3 | 22,486/24,984 | loss 0.3417 | lr 1.11e-06 | 15.6 mnt, sisa ±1.7 mnt
  epoch 3 | 24,984/24,984 | loss 0.3414 | lr 0.00e+00 | 17.3 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 17.3 mnt | val loss 0.5182 | acc 0.7732 P 0.7676 R 0.7756 F1 0.7716 macro-F1 0.7732
[R1_early_distilbert_lr3e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7742 | training 52.5 mnt | memori puncak 2.64 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 903.97it/s]

[R1_late_roberta_lr3e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 127.0 juta (dilatih 127.0 juta)
  epoch 1 |  2,499/24,984 | loss 0.6049 | lr 1.00e-05 | 5.0 mnt, sisa ±45.2 mnt
  epoch 1 |  4,997/24,984 | loss 0.5387 | lr 2.00e-05 | 10.0 mnt, sisa ±40.1 mnt
  epoch 1 |  7,496/24,984 | loss 0.5241 | lr 3.00e-05 | 15.0 mnt, sisa ±35.1 mnt
  epoch 1 |  9,994/24,984 | loss 0.5174 | lr 2.89e-05 | 20.0 mnt, sisa ±30.0 mnt
  epoch 1 | 12,492/24,984 | loss 0.5055 | lr 2.78e-05 | 25.0 mnt, sisa ±25.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.4958 | lr 2.67e-05 | 30.0 mnt, sisa ±20.0 mnt
  epoch 1 | 17,489/24,984 | loss 0.4943 | lr 2.56e-05 | 35.0 mnt, sisa ±15.0 mnt
  epoch 1 | 19,988/24,984 | loss 0.4870 | lr 2.44e-05 | 40.0 mnt, sisa ±10.0 mnt
  epoch 1 | 22,486/24,984 | loss 0.4818 | lr 2.33e-05 | 45.1 mnt, sisa ±5.0 mnt
  epoch 1 | 24,984/24,984 | loss 0.4811 | lr 2.22e-05 | 50.1 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 50.1 mnt | val loss 0.4732 | acc 0.7764 P 0.7746 R 0.7716 F1 0.7731 macro-F1 0.7763
  epoch 2 |  2,499/24,984 | loss 0.4444 | lr 2.11e-05 | 5.0 mnt, sisa ±45.2 mnt
  epoch 2 |  4,997/24,984 | loss 0.4439 | lr 2.00e-05 | 10.1 mnt, sisa ±40.2 mnt
  epoch 2 |  7,496/24,984 | loss 0.4420 | lr 1.89e-05 | 15.0 mnt, sisa ±35.1 mnt
  epoch 2 |  9,994/24,984 | loss 0.4423 | lr 1.78e-05 | 20.0 mnt, sisa ±30.1 mnt
  epoch 2 | 12,492/24,984 | loss 0.4402 | lr 1.67e-05 | 25.1 mnt, sisa ±25.1 mnt
  epoch 2 | 14,991/24,984 | loss 0.4381 | lr 1.56e-05 | 30.1 mnt, sisa ±20.1 mnt
  epoch 2 | 17,489/24,984 | loss 0.4384 | lr 1.44e-05 | 35.1 mnt, sisa ±15.0 mnt
  epoch 2 | 19,988/24,984 | loss 0.4367 | lr 1.33e-05 | 40.1 mnt, sisa ±10.0 mnt
  epoch 2 | 22,486/24,984 | loss 0.4315 | lr 1.22e-05 | 45.1 mnt, sisa ±5.0 mnt
  epoch 2 | 24,984/24,984 | loss 0.4318 | lr 1.11e-05 | 50.1 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 50.1 mnt | val loss 0.4620 | acc 0.7883 P 0.7974 R 0.7658 F1 0.7813 macro-F1 0.7881
  epoch 3 |  2,499/24,984 | loss 0.3838 | lr 1.00e-05 | 5.0 mnt, sisa ±45.1 mnt
  epoch 3 |  4,997/24,984 | loss 0.3776 | lr 8.89e-06 | 10.0 mnt, sisa ±40.0 mnt
  epoch 3 |  7,496/24,984 | loss 0.3782 | lr 7.78e-06 | 15.0 mnt, sisa ±35.1 mnt
  epoch 3 |  9,994/24,984 | loss 0.3766 | lr 6.67e-06 | 20.1 mnt, sisa ±30.1 mnt
  epoch 3 | 12,492/24,984 | loss 0.3769 | lr 5.56e-06 | 25.1 mnt, sisa ±25.1 mnt
  epoch 3 | 14,991/24,984 | loss 0.3748 | lr 4.44e-06 | 30.1 mnt, sisa ±20.1 mnt
  epoch 3 | 17,489/24,984 | loss 0.3713 | lr 3.33e-06 | 35.1 mnt, sisa ±15.0 mnt
  epoch 3 | 19,988/24,984 | loss 0.3727 | lr 2.22e-06 | 40.1 mnt, sisa ±10.0 mnt
  epoch 3 | 22,486/24,984 | loss 0.3728 | lr 1.11e-06 | 45.1 mnt, sisa ±5.0 mnt
  epoch 3 | 24,984/24,984 | loss 0.3713 | lr 0.00e+00 | 50.1 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 50.1 mnt | val loss 0.4770 | acc 0.7893 P 0.7782 R 0.8019 F1 0.7899 macro-F1 0.7893
[R1_late_roberta_lr3e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7893 | training 150.3 mnt | memori puncak 8.38 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1060.96it/s]

[R1_late_distilbert_lr3e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 67.6 juta (dilatih 67.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6183 | lr 1.00e-05 | 2.6 mnt, sisa ±23.3 mnt
  epoch 1 |  4,997/24,984 | loss 0.5490 | lr 2.00e-05 | 5.2 mnt, sisa ±20.7 mnt
  epoch 1 |  7,496/24,984 | loss 0.5326 | lr 3.00e-05 | 7.8 mnt, sisa ±18.1 mnt
  epoch 1 |  9,994/24,984 | loss 0.5235 | lr 2.89e-05 | 10.3 mnt, sisa ±15.5 mnt
  epoch 1 | 12,492/24,984 | loss 0.5092 | lr 2.78e-05 | 12.9 mnt, sisa ±12.9 mnt
  epoch 1 | 14,991/24,984 | loss 0.5025 | lr 2.67e-05 | 15.5 mnt, sisa ±10.3 mnt
  epoch 1 | 17,489/24,984 | loss 0.4992 | lr 2.56e-05 | 18.1 mnt, sisa ±7.7 mnt
  epoch 1 | 19,988/24,984 | loss 0.4963 | lr 2.44e-05 | 20.7 mnt, sisa ±5.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.4936 | lr 2.33e-05 | 23.3 mnt, sisa ±2.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4896 | lr 2.22e-05 | 25.8 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 25.8 mnt | val loss 0.4834 | acc 0.7682 P 0.7864 R 0.7283 F1 0.7562 macro-F1 0.7676
  epoch 2 |  2,499/24,984 | loss 0.4412 | lr 2.11e-05 | 2.6 mnt, sisa ±23.3 mnt
  epoch 2 |  4,997/24,984 | loss 0.4405 | lr 2.00e-05 | 5.2 mnt, sisa ±20.7 mnt
  epoch 2 |  7,496/24,984 | loss 0.4413 | lr 1.89e-05 | 7.8 mnt, sisa ±18.1 mnt
  epoch 2 |  9,994/24,984 | loss 0.4400 | lr 1.78e-05 | 10.3 mnt, sisa ±15.5 mnt
  epoch 2 | 12,492/24,984 | loss 0.4366 | lr 1.67e-05 | 12.9 mnt, sisa ±12.9 mnt
  epoch 2 | 14,991/24,984 | loss 0.4365 | lr 1.56e-05 | 15.5 mnt, sisa ±10.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4347 | lr 1.44e-05 | 18.1 mnt, sisa ±7.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4372 | lr 1.33e-05 | 20.7 mnt, sisa ±5.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4303 | lr 1.22e-05 | 23.3 mnt, sisa ±2.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4326 | lr 1.11e-05 | 25.8 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 25.8 mnt | val loss 0.4730 | acc 0.7756 P 0.7703 R 0.7772 F1 0.7738 macro-F1 0.7755
  epoch 3 |  2,499/24,984 | loss 0.3570 | lr 1.00e-05 | 2.6 mnt, sisa ±23.3 mnt
  epoch 3 |  4,997/24,984 | loss 0.3534 | lr 8.89e-06 | 5.2 mnt, sisa ±20.7 mnt
  epoch 3 |  7,496/24,984 | loss 0.3544 | lr 7.78e-06 | 7.8 mnt, sisa ±18.1 mnt
  epoch 3 |  9,994/24,984 | loss 0.3521 | lr 6.67e-06 | 10.4 mnt, sisa ±15.5 mnt
  epoch 3 | 12,492/24,984 | loss 0.3505 | lr 5.56e-06 | 12.9 mnt, sisa ±12.9 mnt
  epoch 3 | 14,991/24,984 | loss 0.3502 | lr 4.44e-06 | 15.5 mnt, sisa ±10.4 mnt
  epoch 3 | 17,489/24,984 | loss 0.3514 | lr 3.33e-06 | 18.1 mnt, sisa ±7.8 mnt
  epoch 3 | 19,988/24,984 | loss 0.3500 | lr 2.22e-06 | 20.7 mnt, sisa ±5.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.3451 | lr 1.11e-06 | 23.3 mnt, sisa ±2.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.3442 | lr 0.00e+00 | 25.8 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 25.8 mnt | val loss 0.5151 | acc 0.7742 P 0.7722 R 0.7699 F1 0.7710 macro-F1 0.7742
[R1_late_distilbert_lr3e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7755 | training 77.5 mnt | memori puncak 4.28 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1004.80it/s]

[R2_early_roberta_lr1e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6338 | lr 3.33e-06 | 3.3 mnt, sisa ±30.0 mnt
  epoch 1 |  4,997/24,984 | loss 0.5400 | lr 6.67e-06 | 6.6 mnt, sisa ±26.5 mnt
  epoch 1 |  7,496/24,984 | loss 0.5156 | lr 1.00e-05 | 9.9 mnt, sisa ±23.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5046 | lr 9.63e-06 | 13.3 mnt, sisa ±19.9 mnt
  epoch 1 | 12,492/24,984 | loss 0.4905 | lr 9.26e-06 | 16.6 mnt, sisa ±16.6 mnt
  epoch 1 | 14,991/24,984 | loss 0.4790 | lr 8.89e-06 | 19.9 mnt, sisa ±13.2 mnt
  epoch 1 | 17,489/24,984 | loss 0.4789 | lr 8.52e-06 | 23.2 mnt, sisa ±9.9 mnt
  epoch 1 | 19,988/24,984 | loss 0.4693 | lr 8.15e-06 | 26.5 mnt, sisa ±6.6 mnt
  epoch 1 | 22,486/24,984 | loss 0.4665 | lr 7.78e-06 | 29.8 mnt, sisa ±3.3 mnt
  epoch 1 | 24,984/24,984 | loss 0.4669 | lr 7.41e-06 | 33.1 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 33.1 mnt | val loss 0.4558 | acc 0.7853 P 0.7772 R 0.7923 F1 0.7847 macro-F1 0.7853
  epoch 2 |  2,499/24,984 | loss 0.4321 | lr 7.04e-06 | 3.3 mnt, sisa ±30.0 mnt
  epoch 2 |  4,997/24,984 | loss 0.4345 | lr 6.67e-06 | 6.7 mnt, sisa ±26.6 mnt
  epoch 2 |  7,496/24,984 | loss 0.4321 | lr 6.30e-06 | 10.0 mnt, sisa ±23.2 mnt
  epoch 2 |  9,994/24,984 | loss 0.4305 | lr 5.93e-06 | 13.3 mnt, sisa ±19.9 mnt
  epoch 2 | 12,492/24,984 | loss 0.4271 | lr 5.56e-06 | 16.6 mnt, sisa ±16.6 mnt
  epoch 2 | 14,991/24,984 | loss 0.4258 | lr 5.19e-06 | 20.0 mnt, sisa ±13.3 mnt
  epoch 2 | 17,489/24,984 | loss 0.4284 | lr 4.81e-06 | 23.3 mnt, sisa ±10.0 mnt
  epoch 2 | 19,988/24,984 | loss 0.4252 | lr 4.44e-06 | 26.6 mnt, sisa ±6.7 mnt
  epoch 2 | 22,486/24,984 | loss 0.4209 | lr 4.07e-06 | 29.9 mnt, sisa ±3.3 mnt
  epoch 2 | 24,984/24,984 | loss 0.4220 | lr 3.70e-06 | 33.2 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 33.2 mnt | val loss 0.4502 | acc 0.7949 P 0.8007 R 0.7784 F1 0.7894 macro-F1 0.7947
  epoch 3 |  2,499/24,984 | loss 0.3893 | lr 3.33e-06 | 3.3 mnt, sisa ±30.0 mnt
  epoch 3 |  4,997/24,984 | loss 0.3845 | lr 2.96e-06 | 6.6 mnt, sisa ±26.6 mnt
  epoch 3 |  7,496/24,984 | loss 0.3850 | lr 2.59e-06 | 10.0 mnt, sisa ±23.3 mnt
  epoch 3 |  9,994/24,984 | loss 0.3861 | lr 2.22e-06 | 13.3 mnt, sisa ±19.9 mnt
  epoch 3 | 12,492/24,984 | loss 0.3827 | lr 1.85e-06 | 16.6 mnt, sisa ±16.6 mnt
  epoch 3 | 14,991/24,984 | loss 0.3843 | lr 1.48e-06 | 19.9 mnt, sisa ±13.3 mnt
  epoch 3 | 17,489/24,984 | loss 0.3815 | lr 1.11e-06 | 23.3 mnt, sisa ±10.0 mnt
  epoch 3 | 19,988/24,984 | loss 0.3828 | lr 7.41e-07 | 26.6 mnt, sisa ±6.6 mnt
  epoch 3 | 22,486/24,984 | loss 0.3837 | lr 3.70e-07 | 29.8 mnt, sisa ±3.3 mnt
  epoch 3 | 24,984/24,984 | loss 0.3822 | lr 0.00e+00 | 33.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 33.2 mnt | val loss 0.4579 | acc 0.7962 P 0.7850 R 0.8087 F1 0.7967 macro-F1 0.7962
[R2_early_roberta_lr1e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7962 | training 99.5 mnt | memori puncak 5.11 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1025.43it/s]

[R2_early_distilbert_lr1e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6486 | lr 3.33e-06 | 1.7 mnt, sisa ±15.7 mnt
  epoch 1 |  4,997/24,984 | loss 0.5709 | lr 6.67e-06 | 3.5 mnt, sisa ±13.8 mnt
  epoch 1 |  7,496/24,984 | loss 0.5459 | lr 1.00e-05 | 5.2 mnt, sisa ±12.1 mnt
  epoch 1 |  9,994/24,984 | loss 0.5314 | lr 9.63e-06 | 6.9 mnt, sisa ±10.4 mnt
  epoch 1 | 12,492/24,984 | loss 0.5163 | lr 9.26e-06 | 8.6 mnt, sisa ±8.6 mnt
  epoch 1 | 14,991/24,984 | loss 0.5089 | lr 8.89e-06 | 10.4 mnt, sisa ±6.9 mnt
  epoch 1 | 17,489/24,984 | loss 0.5053 | lr 8.52e-06 | 12.1 mnt, sisa ±5.2 mnt
  epoch 1 | 19,988/24,984 | loss 0.5017 | lr 8.15e-06 | 13.8 mnt, sisa ±3.5 mnt
  epoch 1 | 22,486/24,984 | loss 0.4979 | lr 7.78e-06 | 15.6 mnt, sisa ±1.7 mnt
  epoch 1 | 24,984/24,984 | loss 0.4948 | lr 7.41e-06 | 17.3 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 17.3 mnt | val loss 0.4856 | acc 0.7638 P 0.7805 R 0.7257 F1 0.7521 macro-F1 0.7632
  epoch 2 |  2,499/24,984 | loss 0.4623 | lr 7.04e-06 | 1.7 mnt, sisa ±15.6 mnt
  epoch 2 |  4,997/24,984 | loss 0.4597 | lr 6.67e-06 | 3.5 mnt, sisa ±13.9 mnt
  epoch 2 |  7,496/24,984 | loss 0.4620 | lr 6.30e-06 | 5.2 mnt, sisa ±12.1 mnt
  epoch 2 |  9,994/24,984 | loss 0.4608 | lr 5.93e-06 | 6.9 mnt, sisa ±10.4 mnt
  epoch 2 | 12,492/24,984 | loss 0.4563 | lr 5.56e-06 | 8.6 mnt, sisa ±8.6 mnt
  epoch 2 | 14,991/24,984 | loss 0.4560 | lr 5.19e-06 | 10.4 mnt, sisa ±6.9 mnt
  epoch 2 | 17,489/24,984 | loss 0.4541 | lr 4.81e-06 | 12.1 mnt, sisa ±5.2 mnt
  epoch 2 | 19,988/24,984 | loss 0.4564 | lr 4.44e-06 | 13.9 mnt, sisa ±3.5 mnt
  epoch 2 | 22,486/24,984 | loss 0.4500 | lr 4.07e-06 | 15.6 mnt, sisa ±1.7 mnt
  epoch 2 | 24,984/24,984 | loss 0.4546 | lr 3.70e-06 | 17.3 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 17.3 mnt | val loss 0.4761 | acc 0.7714 P 0.7624 R 0.7801 F1 0.7711 macro-F1 0.7714
  epoch 3 |  2,499/24,984 | loss 0.4167 | lr 3.33e-06 | 1.7 mnt, sisa ±15.7 mnt
  epoch 3 |  4,997/24,984 | loss 0.4187 | lr 2.96e-06 | 3.5 mnt, sisa ±13.9 mnt
  epoch 3 |  7,496/24,984 | loss 0.4144 | lr 2.59e-06 | 5.2 mnt, sisa ±12.2 mnt
  epoch 3 |  9,994/24,984 | loss 0.4144 | lr 2.22e-06 | 6.9 mnt, sisa ±10.4 mnt
  epoch 3 | 12,492/24,984 | loss 0.4142 | lr 1.85e-06 | 8.7 mnt, sisa ±8.7 mnt
  epoch 3 | 14,991/24,984 | loss 0.4143 | lr 1.48e-06 | 10.4 mnt, sisa ±6.9 mnt
  epoch 3 | 17,489/24,984 | loss 0.4156 | lr 1.11e-06 | 12.1 mnt, sisa ±5.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.4165 | lr 7.41e-07 | 13.9 mnt, sisa ±3.5 mnt
  epoch 3 | 22,486/24,984 | loss 0.4105 | lr 3.70e-07 | 15.6 mnt, sisa ±1.7 mnt
  epoch 3 | 24,984/24,984 | loss 0.4097 | lr 0.00e+00 | 17.3 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 17.3 mnt | val loss 0.4821 | acc 0.7732 P 0.7714 R 0.7683 F1 0.7699 macro-F1 0.7731
[R2_early_distilbert_lr1e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7731 | training 51.9 mnt | memori puncak 2.64 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 887.38it/s]

[R2_early_roberta_lr2e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6113 | lr 6.67e-06 | 3.3 mnt, sisa ±30.0 mnt
  epoch 1 |  4,997/24,984 | loss 0.5314 | lr 1.33e-05 | 6.6 mnt, sisa ±26.5 mnt
  epoch 1 |  7,496/24,984 | loss 0.5142 | lr 2.00e-05 | 9.9 mnt, sisa ±23.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5047 | lr 1.93e-05 | 13.3 mnt, sisa ±19.9 mnt
  epoch 1 | 12,492/24,984 | loss 0.4919 | lr 1.85e-05 | 16.6 mnt, sisa ±16.6 mnt
  epoch 1 | 14,991/24,984 | loss 0.4810 | lr 1.78e-05 | 19.9 mnt, sisa ±13.2 mnt
  epoch 1 | 17,489/24,984 | loss 0.4806 | lr 1.70e-05 | 23.2 mnt, sisa ±9.9 mnt
  epoch 1 | 19,988/24,984 | loss 0.4722 | lr 1.63e-05 | 26.5 mnt, sisa ±6.6 mnt
  epoch 1 | 22,486/24,984 | loss 0.4676 | lr 1.56e-05 | 29.8 mnt, sisa ±3.3 mnt
  epoch 1 | 24,984/24,984 | loss 0.4676 | lr 1.48e-05 | 33.1 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 33.1 mnt | val loss 0.4586 | acc 0.7846 P 0.7748 R 0.7948 F1 0.7847 macro-F1 0.7846
  epoch 2 |  2,499/24,984 | loss 0.4260 | lr 1.41e-05 | 3.3 mnt, sisa ±30.0 mnt
  epoch 2 |  4,997/24,984 | loss 0.4273 | lr 1.33e-05 | 6.7 mnt, sisa ±26.6 mnt
  epoch 2 |  7,496/24,984 | loss 0.4258 | lr 1.26e-05 | 10.0 mnt, sisa ±23.2 mnt
  epoch 2 |  9,994/24,984 | loss 0.4237 | lr 1.19e-05 | 13.3 mnt, sisa ±19.9 mnt
  epoch 2 | 12,492/24,984 | loss 0.4220 | lr 1.11e-05 | 16.6 mnt, sisa ±16.6 mnt
  epoch 2 | 14,991/24,984 | loss 0.4191 | lr 1.04e-05 | 19.9 mnt, sisa ±13.3 mnt
  epoch 2 | 17,489/24,984 | loss 0.4214 | lr 9.63e-06 | 23.2 mnt, sisa ±9.9 mnt
  epoch 2 | 19,988/24,984 | loss 0.4175 | lr 8.89e-06 | 26.5 mnt, sisa ±6.6 mnt
  epoch 2 | 22,486/24,984 | loss 0.4138 | lr 8.15e-06 | 29.8 mnt, sisa ±3.3 mnt
  epoch 2 | 24,984/24,984 | loss 0.4150 | lr 7.41e-06 | 33.1 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 33.1 mnt | val loss 0.4545 | acc 0.7951 P 0.7972 R 0.7847 F1 0.7909 macro-F1 0.7950
  epoch 3 |  2,499/24,984 | loss 0.3645 | lr 6.67e-06 | 3.3 mnt, sisa ±30.0 mnt
  epoch 3 |  4,997/24,984 | loss 0.3590 | lr 5.93e-06 | 6.6 mnt, sisa ±26.5 mnt
  epoch 3 |  7,496/24,984 | loss 0.3616 | lr 5.18e-06 | 10.0 mnt, sisa ±23.2 mnt
  epoch 3 |  9,994/24,984 | loss 0.3600 | lr 4.44e-06 | 13.3 mnt, sisa ±19.9 mnt
  epoch 3 | 12,492/24,984 | loss 0.3572 | lr 3.70e-06 | 16.6 mnt, sisa ±16.6 mnt
  epoch 3 | 14,991/24,984 | loss 0.3601 | lr 2.96e-06 | 19.9 mnt, sisa ±13.3 mnt
  epoch 3 | 17,489/24,984 | loss 0.3545 | lr 2.22e-06 | 23.2 mnt, sisa ±10.0 mnt
  epoch 3 | 19,988/24,984 | loss 0.3555 | lr 1.48e-06 | 26.5 mnt, sisa ±6.6 mnt
  epoch 3 | 22,486/24,984 | loss 0.3568 | lr 7.41e-07 | 29.8 mnt, sisa ±3.3 mnt
  epoch 3 | 24,984/24,984 | loss 0.3544 | lr 0.00e+00 | 33.1 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 33.1 mnt | val loss 0.4717 | acc 0.7948 P 0.7809 R 0.8123 F1 0.7963 macro-F1 0.7948
[R2_early_roberta_lr2e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7950 | training 99.4 mnt | memori puncak 5.11 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 958.34it/s]

[R2_early_distilbert_lr2e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6287 | lr 6.67e-06 | 1.7 mnt, sisa ±15.7 mnt
  epoch 1 |  4,997/24,984 | loss 0.5584 | lr 1.33e-05 | 3.5 mnt, sisa ±13.9 mnt
  epoch 1 |  7,496/24,984 | loss 0.5373 | lr 2.00e-05 | 5.2 mnt, sisa ±12.1 mnt
  epoch 1 |  9,994/24,984 | loss 0.5255 | lr 1.93e-05 | 6.9 mnt, sisa ±10.4 mnt
  epoch 1 | 12,492/24,984 | loss 0.5110 | lr 1.85e-05 | 8.6 mnt, sisa ±8.6 mnt
  epoch 1 | 14,991/24,984 | loss 0.5047 | lr 1.78e-05 | 10.4 mnt, sisa ±6.9 mnt
  epoch 1 | 17,489/24,984 | loss 0.4991 | lr 1.70e-05 | 12.1 mnt, sisa ±5.2 mnt
  epoch 1 | 19,988/24,984 | loss 0.4970 | lr 1.63e-05 | 13.8 mnt, sisa ±3.5 mnt
  epoch 1 | 22,486/24,984 | loss 0.4923 | lr 1.56e-05 | 15.6 mnt, sisa ±1.7 mnt
  epoch 1 | 24,984/24,984 | loss 0.4897 | lr 1.48e-05 | 17.3 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 17.3 mnt | val loss 0.4808 | acc 0.7681 P 0.7833 R 0.7333 F1 0.7575 macro-F1 0.7677
  epoch 2 |  2,499/24,984 | loss 0.4447 | lr 1.41e-05 | 1.7 mnt, sisa ±15.6 mnt
  epoch 2 |  4,997/24,984 | loss 0.4427 | lr 1.33e-05 | 3.5 mnt, sisa ±13.9 mnt
  epoch 2 |  7,496/24,984 | loss 0.4453 | lr 1.26e-05 | 5.2 mnt, sisa ±12.1 mnt
  epoch 2 |  9,994/24,984 | loss 0.4433 | lr 1.19e-05 | 6.9 mnt, sisa ±10.4 mnt
  epoch 2 | 12,492/24,984 | loss 0.4388 | lr 1.11e-05 | 8.7 mnt, sisa ±8.7 mnt
  epoch 2 | 14,991/24,984 | loss 0.4387 | lr 1.04e-05 | 10.5 mnt, sisa ±7.0 mnt
  epoch 2 | 17,489/24,984 | loss 0.4374 | lr 9.63e-06 | 12.3 mnt, sisa ±5.3 mnt
  epoch 2 | 19,988/24,984 | loss 0.4388 | lr 8.89e-06 | 14.1 mnt, sisa ±3.5 mnt
  epoch 2 | 22,486/24,984 | loss 0.4337 | lr 8.15e-06 | 15.8 mnt, sisa ±1.8 mnt
  epoch 2 | 24,984/24,984 | loss 0.4376 | lr 7.41e-06 | 17.5 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 17.5 mnt | val loss 0.4739 | acc 0.7742 P 0.7651 R 0.7831 F1 0.7740 macro-F1 0.7742
  epoch 3 |  2,499/24,984 | loss 0.3731 | lr 6.67e-06 | 1.7 mnt, sisa ±15.6 mnt
  epoch 3 |  4,997/24,984 | loss 0.3752 | lr 5.93e-06 | 3.5 mnt, sisa ±13.8 mnt
  epoch 3 |  7,496/24,984 | loss 0.3708 | lr 5.18e-06 | 5.2 mnt, sisa ±12.1 mnt
  epoch 3 |  9,994/24,984 | loss 0.3696 | lr 4.44e-06 | 6.9 mnt, sisa ±10.4 mnt
  epoch 3 | 12,492/24,984 | loss 0.3687 | lr 3.70e-06 | 8.6 mnt, sisa ±8.6 mnt
  epoch 3 | 14,991/24,984 | loss 0.3682 | lr 2.96e-06 | 10.3 mnt, sisa ±6.9 mnt
  epoch 3 | 17,489/24,984 | loss 0.3706 | lr 2.22e-06 | 12.1 mnt, sisa ±5.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.3699 | lr 1.48e-06 | 13.8 mnt, sisa ±3.4 mnt
  epoch 3 | 22,486/24,984 | loss 0.3641 | lr 7.41e-07 | 15.5 mnt, sisa ±1.7 mnt
  epoch 3 | 24,984/24,984 | loss 0.3645 | lr 0.00e+00 | 17.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 17.2 mnt | val loss 0.5004 | acc 0.7745 P 0.7705 R 0.7737 F1 0.7721 macro-F1 0.7744
[R2_early_distilbert_lr2e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7744 | training 52.0 mnt | memori puncak 2.64 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1092.73it/s]

[R2_early_roberta_lr5e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.5889 | lr 1.67e-05 | 3.3 mnt, sisa ±29.6 mnt
  epoch 1 |  4,997/24,984 | loss 0.5324 | lr 3.33e-05 | 6.5 mnt, sisa ±26.2 mnt
  epoch 1 |  7,496/24,984 | loss 0.5271 | lr 5.00e-05 | 9.8 mnt, sisa ±22.9 mnt
  epoch 1 |  9,994/24,984 | loss 0.5250 | lr 4.81e-05 | 13.1 mnt, sisa ±19.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5132 | lr 4.63e-05 | 16.3 mnt, sisa ±16.3 mnt
  epoch 1 | 14,991/24,984 | loss 0.5071 | lr 4.44e-05 | 19.6 mnt, sisa ±13.1 mnt
  epoch 1 | 17,489/24,984 | loss 0.5060 | lr 4.26e-05 | 22.9 mnt, sisa ±9.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.5061 | lr 4.07e-05 | 26.1 mnt, sisa ±6.5 mnt
  epoch 1 | 22,486/24,984 | loss 0.5152 | lr 3.89e-05 | 29.4 mnt, sisa ±3.3 mnt
  epoch 1 | 24,984/24,984 | loss 0.5140 | lr 3.70e-05 | 32.7 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 32.7 mnt | val loss 0.5091 | acc 0.7646 P 0.7624 R 0.7602 F1 0.7613 macro-F1 0.7645
  epoch 2 |  2,499/24,984 | loss 0.4770 | lr 3.52e-05 | 3.3 mnt, sisa ±29.6 mnt
  epoch 2 |  4,997/24,984 | loss 0.4744 | lr 3.33e-05 | 6.6 mnt, sisa ±26.3 mnt
  epoch 2 |  7,496/24,984 | loss 0.4742 | lr 3.15e-05 | 9.8 mnt, sisa ±22.9 mnt
  epoch 2 |  9,994/24,984 | loss 0.4694 | lr 2.96e-05 | 13.1 mnt, sisa ±19.6 mnt
  epoch 2 | 12,492/24,984 | loss 0.4652 | lr 2.78e-05 | 16.4 mnt, sisa ±16.4 mnt
  epoch 2 | 14,991/24,984 | loss 0.4634 | lr 2.59e-05 | 19.7 mnt, sisa ±13.1 mnt
  epoch 2 | 17,489/24,984 | loss 0.4671 | lr 2.41e-05 | 22.9 mnt, sisa ±9.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4593 | lr 2.22e-05 | 26.2 mnt, sisa ±6.5 mnt
  epoch 2 | 22,486/24,984 | loss 0.4578 | lr 2.04e-05 | 29.4 mnt, sisa ±3.3 mnt
  epoch 2 | 24,984/24,984 | loss 0.4534 | lr 1.85e-05 | 32.7 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 32.7 mnt | val loss 0.4695 | acc 0.7819 P 0.7974 R 0.7486 F1 0.7722 macro-F1 0.7815
  epoch 3 |  2,499/24,984 | loss 0.4158 | lr 1.67e-05 | 3.3 mnt, sisa ±29.7 mnt
  epoch 3 |  4,997/24,984 | loss 0.4090 | lr 1.48e-05 | 6.6 mnt, sisa ±26.2 mnt
  epoch 3 |  7,496/24,984 | loss 0.4075 | lr 1.30e-05 | 9.8 mnt, sisa ±23.0 mnt
  epoch 3 |  9,994/24,984 | loss 0.4035 | lr 1.11e-05 | 13.1 mnt, sisa ±19.7 mnt
  epoch 3 | 12,492/24,984 | loss 0.4013 | lr 9.26e-06 | 16.5 mnt, sisa ±16.5 mnt
  epoch 3 | 14,991/24,984 | loss 0.4032 | lr 7.41e-06 | 20.0 mnt, sisa ±13.3 mnt
  epoch 3 | 17,489/24,984 | loss 0.3971 | lr 5.56e-06 | 23.4 mnt, sisa ±10.0 mnt
  epoch 3 | 19,988/24,984 | loss 0.3967 | lr 3.70e-06 | 26.7 mnt, sisa ±6.7 mnt
  epoch 3 | 22,486/24,984 | loss 0.3961 | lr 1.85e-06 | 29.9 mnt, sisa ±3.3 mnt
  epoch 3 | 24,984/24,984 | loss 0.3954 | lr 0.00e+00 | 33.3 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 33.3 mnt | val loss 0.4733 | acc 0.7854 P 0.7755 R 0.7957 F1 0.7855 macro-F1 0.7854
[R2_early_roberta_lr5e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7854 | training 98.6 mnt | memori puncak 5.11 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1088.57it/s]

[R2_early_distilbert_lr5e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6081 | lr 1.67e-05 | 1.7 mnt, sisa ±15.6 mnt
  epoch 1 |  4,997/24,984 | loss 0.5500 | lr 3.33e-05 | 3.5 mnt, sisa ±13.8 mnt
  epoch 1 |  7,496/24,984 | loss 0.5364 | lr 5.00e-05 | 5.2 mnt, sisa ±12.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5300 | lr 4.81e-05 | 7.0 mnt, sisa ±10.5 mnt
  epoch 1 | 12,492/24,984 | loss 0.5177 | lr 4.63e-05 | 8.7 mnt, sisa ±8.7 mnt
  epoch 1 | 14,991/24,984 | loss 0.5112 | lr 4.44e-05 | 10.4 mnt, sisa ±7.0 mnt
  epoch 1 | 17,489/24,984 | loss 0.5071 | lr 4.26e-05 | 12.1 mnt, sisa ±5.2 mnt
  epoch 1 | 19,988/24,984 | loss 0.5054 | lr 4.07e-05 | 13.9 mnt, sisa ±3.5 mnt
  epoch 1 | 22,486/24,984 | loss 0.5017 | lr 3.89e-05 | 15.6 mnt, sisa ±1.7 mnt
  epoch 1 | 24,984/24,984 | loss 0.4976 | lr 3.70e-05 | 17.3 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 17.3 mnt | val loss 0.4908 | acc 0.7637 P 0.7808 R 0.7252 F1 0.7519 macro-F1 0.7632
  epoch 2 |  2,499/24,984 | loss 0.4459 | lr 3.52e-05 | 1.7 mnt, sisa ±15.6 mnt
  epoch 2 |  4,997/24,984 | loss 0.4449 | lr 3.33e-05 | 3.5 mnt, sisa ±13.9 mnt
  epoch 2 |  7,496/24,984 | loss 0.4474 | lr 3.15e-05 | 5.2 mnt, sisa ±12.1 mnt
  epoch 2 |  9,994/24,984 | loss 0.4476 | lr 2.96e-05 | 6.9 mnt, sisa ±10.4 mnt
  epoch 2 | 12,492/24,984 | loss 0.4427 | lr 2.78e-05 | 8.6 mnt, sisa ±8.6 mnt
  epoch 2 | 14,991/24,984 | loss 0.4420 | lr 2.59e-05 | 10.4 mnt, sisa ±6.9 mnt
  epoch 2 | 17,489/24,984 | loss 0.4419 | lr 2.41e-05 | 12.1 mnt, sisa ±5.2 mnt
  epoch 2 | 19,988/24,984 | loss 0.4421 | lr 2.22e-05 | 13.8 mnt, sisa ±3.5 mnt
  epoch 2 | 22,486/24,984 | loss 0.4351 | lr 2.04e-05 | 15.5 mnt, sisa ±1.7 mnt
  epoch 2 | 24,984/24,984 | loss 0.4383 | lr 1.85e-05 | 17.3 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 17.3 mnt | val loss 0.4779 | acc 0.7715 P 0.7639 R 0.7776 F1 0.7707 macro-F1 0.7715
  epoch 3 |  2,499/24,984 | loss 0.3453 | lr 1.67e-05 | 1.7 mnt, sisa ±15.6 mnt
  epoch 3 |  4,997/24,984 | loss 0.3458 | lr 1.48e-05 | 3.5 mnt, sisa ±13.8 mnt
  epoch 3 |  7,496/24,984 | loss 0.3454 | lr 1.30e-05 | 5.2 mnt, sisa ±12.1 mnt
  epoch 3 |  9,994/24,984 | loss 0.3400 | lr 1.11e-05 | 6.9 mnt, sisa ±10.4 mnt
  epoch 3 | 12,492/24,984 | loss 0.3381 | lr 9.26e-06 | 8.7 mnt, sisa ±8.7 mnt
  epoch 3 | 14,991/24,984 | loss 0.3383 | lr 7.41e-06 | 10.4 mnt, sisa ±7.0 mnt
  epoch 3 | 17,489/24,984 | loss 0.3392 | lr 5.56e-06 | 12.2 mnt, sisa ±5.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.3361 | lr 3.70e-06 | 14.0 mnt, sisa ±3.5 mnt
  epoch 3 | 22,486/24,984 | loss 0.3319 | lr 1.85e-06 | 15.8 mnt, sisa ±1.8 mnt
  epoch 3 | 24,984/24,984 | loss 0.3315 | lr 0.00e+00 | 17.5 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 17.5 mnt | val loss 0.5350 | acc 0.7688 P 0.7654 R 0.7667 F1 0.7660 macro-F1 0.7687
[R2_early_distilbert_lr5e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7715 | training 52.1 mnt | memori puncak 2.64 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 896.37it/s]

[R3_comment_roberta_lr1e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6251 | lr 3.33e-06 | 3.2 mnt, sisa ±28.9 mnt
  epoch 1 |  4,997/24,984 | loss 0.5447 | lr 6.67e-06 | 6.4 mnt, sisa ±25.6 mnt
  epoch 1 |  7,496/24,984 | loss 0.5277 | lr 1.00e-05 | 9.5 mnt, sisa ±22.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5119 | lr 9.63e-06 | 12.6 mnt, sisa ±18.9 mnt
  epoch 1 | 12,492/24,984 | loss 0.5027 | lr 9.26e-06 | 15.7 mnt, sisa ±15.7 mnt
  epoch 1 | 14,991/24,984 | loss 0.4967 | lr 8.89e-06 | 18.9 mnt, sisa ±12.6 mnt
  epoch 1 | 17,489/24,984 | loss 0.4927 | lr 8.52e-06 | 22.1 mnt, sisa ±9.5 mnt
  epoch 1 | 19,988/24,984 | loss 0.4871 | lr 8.15e-06 | 25.3 mnt, sisa ±6.3 mnt
  epoch 1 | 22,486/24,984 | loss 0.4819 | lr 7.78e-06 | 28.4 mnt, sisa ±3.2 mnt
  epoch 1 | 24,984/24,984 | loss 0.4830 | lr 7.41e-06 | 31.5 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 31.5 mnt | val loss 0.4758 | acc 0.7749 P 0.7988 R 0.7272 F1 0.7613 macro-F1 0.7741
  epoch 2 |  2,499/24,984 | loss 0.4561 | lr 7.04e-06 | 3.1 mnt, sisa ±27.9 mnt
  epoch 2 |  4,997/24,984 | loss 0.4510 | lr 6.67e-06 | 6.2 mnt, sisa ±24.8 mnt
  epoch 2 |  7,496/24,984 | loss 0.4529 | lr 6.30e-06 | 9.3 mnt, sisa ±21.6 mnt
  epoch 2 |  9,994/24,984 | loss 0.4531 | lr 5.93e-06 | 12.4 mnt, sisa ±18.5 mnt
  epoch 2 | 12,492/24,984 | loss 0.4514 | lr 5.56e-06 | 15.4 mnt, sisa ±15.4 mnt
  epoch 2 | 14,991/24,984 | loss 0.4506 | lr 5.19e-06 | 18.6 mnt, sisa ±12.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4496 | lr 4.81e-06 | 21.7 mnt, sisa ±9.3 mnt
  epoch 2 | 19,988/24,984 | loss 0.4504 | lr 4.44e-06 | 24.8 mnt, sisa ±6.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4441 | lr 4.07e-06 | 27.9 mnt, sisa ±3.1 mnt
  epoch 2 | 24,984/24,984 | loss 0.4453 | lr 3.70e-06 | 31.0 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 31.0 mnt | val loss 0.4695 | acc 0.7804 P 0.7748 R 0.7828 F1 0.7788 macro-F1 0.7804
  epoch 3 |  2,499/24,984 | loss 0.4162 | lr 3.33e-06 | 3.1 mnt, sisa ±27.9 mnt
  epoch 3 |  4,997/24,984 | loss 0.4162 | lr 2.96e-06 | 6.2 mnt, sisa ±24.8 mnt
  epoch 3 |  7,496/24,984 | loss 0.4137 | lr 2.59e-06 | 9.3 mnt, sisa ±21.7 mnt
  epoch 3 |  9,994/24,984 | loss 0.4123 | lr 2.22e-06 | 12.4 mnt, sisa ±18.6 mnt
  epoch 3 | 12,492/24,984 | loss 0.4161 | lr 1.85e-06 | 15.5 mnt, sisa ±15.5 mnt
  epoch 3 | 14,991/24,984 | loss 0.4146 | lr 1.48e-06 | 18.6 mnt, sisa ±12.4 mnt
  epoch 3 | 17,489/24,984 | loss 0.4100 | lr 1.11e-06 | 21.7 mnt, sisa ±9.3 mnt
  epoch 3 | 19,988/24,984 | loss 0.4148 | lr 7.41e-07 | 24.7 mnt, sisa ±6.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.4095 | lr 3.70e-07 | 27.8 mnt, sisa ±3.1 mnt
  epoch 3 | 24,984/24,984 | loss 0.4099 | lr 0.00e+00 | 30.9 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 30.9 mnt | val loss 0.4773 | acc 0.7827 P 0.7796 R 0.7808 F1 0.7802 macro-F1 0.7827
[R3_comment_roberta_lr1e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7827 | training 93.4 mnt | memori puncak 5.08 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1105.11it/s]

[R3_comment_distilbert_lr1e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6369 | lr 3.33e-06 | 1.6 mnt, sisa ±14.4 mnt
  epoch 1 |  4,997/24,984 | loss 0.5657 | lr 6.67e-06 | 3.2 mnt, sisa ±12.8 mnt
  epoch 1 |  7,496/24,984 | loss 0.5461 | lr 1.00e-05 | 4.8 mnt, sisa ±11.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5293 | lr 9.63e-06 | 6.4 mnt, sisa ±9.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5173 | lr 9.26e-06 | 8.0 mnt, sisa ±8.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.5160 | lr 8.89e-06 | 9.6 mnt, sisa ±6.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.5077 | lr 8.52e-06 | 11.2 mnt, sisa ±4.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.5024 | lr 8.15e-06 | 12.8 mnt, sisa ±3.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.5002 | lr 7.78e-06 | 14.4 mnt, sisa ±1.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4990 | lr 7.41e-06 | 16.0 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 16.0 mnt | val loss 0.5002 | acc 0.7566 P 0.7471 R 0.7665 F1 0.7567 macro-F1 0.7566
  epoch 2 |  2,499/24,984 | loss 0.4721 | lr 7.04e-06 | 1.6 mnt, sisa ±14.4 mnt
  epoch 2 |  4,997/24,984 | loss 0.4661 | lr 6.67e-06 | 3.2 mnt, sisa ±12.8 mnt
  epoch 2 |  7,496/24,984 | loss 0.4698 | lr 6.30e-06 | 4.8 mnt, sisa ±11.2 mnt
  epoch 2 |  9,994/24,984 | loss 0.4708 | lr 5.93e-06 | 6.4 mnt, sisa ±9.6 mnt
  epoch 2 | 12,492/24,984 | loss 0.4652 | lr 5.56e-06 | 8.0 mnt, sisa ±8.0 mnt
  epoch 2 | 14,991/24,984 | loss 0.4661 | lr 5.19e-06 | 9.6 mnt, sisa ±6.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4647 | lr 4.81e-06 | 11.2 mnt, sisa ±4.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4666 | lr 4.44e-06 | 12.8 mnt, sisa ±3.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4600 | lr 4.07e-06 | 14.4 mnt, sisa ±1.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4626 | lr 3.70e-06 | 16.0 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 16.0 mnt | val loss 0.4856 | acc 0.7655 P 0.7753 R 0.7393 F1 0.7569 macro-F1 0.7652
  epoch 3 |  2,499/24,984 | loss 0.4317 | lr 3.33e-06 | 1.6 mnt, sisa ±14.4 mnt
  epoch 3 |  4,997/24,984 | loss 0.4296 | lr 2.96e-06 | 3.2 mnt, sisa ±12.8 mnt
  epoch 3 |  7,496/24,984 | loss 0.4321 | lr 2.59e-06 | 4.8 mnt, sisa ±11.2 mnt
  epoch 3 |  9,994/24,984 | loss 0.4277 | lr 2.22e-06 | 6.4 mnt, sisa ±9.6 mnt
  epoch 3 | 12,492/24,984 | loss 0.4290 | lr 1.85e-06 | 8.0 mnt, sisa ±8.0 mnt
  epoch 3 | 14,991/24,984 | loss 0.4266 | lr 1.48e-06 | 9.6 mnt, sisa ±6.4 mnt
  epoch 3 | 17,489/24,984 | loss 0.4285 | lr 1.11e-06 | 11.2 mnt, sisa ±4.8 mnt
  epoch 3 | 19,988/24,984 | loss 0.4318 | lr 7.41e-07 | 12.8 mnt, sisa ±3.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.4288 | lr 3.70e-07 | 14.4 mnt, sisa ±1.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.4223 | lr 0.00e+00 | 16.0 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 16.0 mnt | val loss 0.4934 | acc 0.7673 P 0.7687 R 0.7562 F1 0.7624 macro-F1 0.7672
[R3_comment_distilbert_lr1e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7672 | training 48.0 mnt | memori puncak 2.63 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 898.18it/s]

[R3_comment_roberta_lr2e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6058 | lr 6.67e-06 | 3.1 mnt, sisa ±27.8 mnt
  epoch 1 |  4,997/24,984 | loss 0.5376 | lr 1.33e-05 | 6.2 mnt, sisa ±24.7 mnt
  epoch 1 |  7,496/24,984 | loss 0.5273 | lr 2.00e-05 | 9.3 mnt, sisa ±21.6 mnt
  epoch 1 |  9,994/24,984 | loss 0.5128 | lr 1.93e-05 | 12.3 mnt, sisa ±18.5 mnt
  epoch 1 | 12,492/24,984 | loss 0.5048 | lr 1.85e-05 | 15.4 mnt, sisa ±15.4 mnt
  epoch 1 | 14,991/24,984 | loss 0.4985 | lr 1.78e-05 | 18.5 mnt, sisa ±12.3 mnt
  epoch 1 | 17,489/24,984 | loss 0.4949 | lr 1.70e-05 | 21.6 mnt, sisa ±9.3 mnt
  epoch 1 | 19,988/24,984 | loss 0.4891 | lr 1.63e-05 | 24.7 mnt, sisa ±6.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.4842 | lr 1.56e-05 | 27.8 mnt, sisa ±3.1 mnt
  epoch 1 | 24,984/24,984 | loss 0.4845 | lr 1.48e-05 | 30.9 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 30.9 mnt | val loss 0.4724 | acc 0.7763 P 0.7969 R 0.7340 F1 0.7641 macro-F1 0.7757
  epoch 2 |  2,499/24,984 | loss 0.4497 | lr 1.41e-05 | 3.1 mnt, sisa ±27.9 mnt
  epoch 2 |  4,997/24,984 | loss 0.4465 | lr 1.33e-05 | 6.2 mnt, sisa ±24.9 mnt
  epoch 2 |  7,496/24,984 | loss 0.4470 | lr 1.26e-05 | 9.4 mnt, sisa ±21.8 mnt
  epoch 2 |  9,994/24,984 | loss 0.4491 | lr 1.19e-05 | 12.5 mnt, sisa ±18.8 mnt
  epoch 2 | 12,492/24,984 | loss 0.4469 | lr 1.11e-05 | 15.6 mnt, sisa ±15.6 mnt
  epoch 2 | 14,991/24,984 | loss 0.4460 | lr 1.04e-05 | 18.7 mnt, sisa ±12.5 mnt
  epoch 2 | 17,489/24,984 | loss 0.4457 | lr 9.63e-06 | 21.8 mnt, sisa ±9.3 mnt
  epoch 2 | 19,988/24,984 | loss 0.4447 | lr 8.89e-06 | 24.9 mnt, sisa ±6.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4374 | lr 8.15e-06 | 28.0 mnt, sisa ±3.1 mnt
  epoch 2 | 24,984/24,984 | loss 0.4405 | lr 7.41e-06 | 31.0 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 31.0 mnt | val loss 0.4672 | acc 0.7822 P 0.7825 R 0.7740 F1 0.7782 macro-F1 0.7821
  epoch 3 |  2,499/24,984 | loss 0.3954 | lr 6.67e-06 | 3.1 mnt, sisa ±27.7 mnt
  epoch 3 |  4,997/24,984 | loss 0.3980 | lr 5.93e-06 | 6.2 mnt, sisa ±24.7 mnt
  epoch 3 |  7,496/24,984 | loss 0.3947 | lr 5.18e-06 | 9.3 mnt, sisa ±21.6 mnt
  epoch 3 |  9,994/24,984 | loss 0.3913 | lr 4.44e-06 | 12.3 mnt, sisa ±18.5 mnt
  epoch 3 | 12,492/24,984 | loss 0.3952 | lr 3.70e-06 | 15.4 mnt, sisa ±15.4 mnt
  epoch 3 | 14,991/24,984 | loss 0.3947 | lr 2.96e-06 | 18.5 mnt, sisa ±12.3 mnt
  epoch 3 | 17,489/24,984 | loss 0.3885 | lr 2.22e-06 | 21.6 mnt, sisa ±9.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.3927 | lr 1.48e-06 | 24.7 mnt, sisa ±6.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.3871 | lr 7.41e-07 | 27.7 mnt, sisa ±3.1 mnt
  epoch 3 | 24,984/24,984 | loss 0.3886 | lr 0.00e+00 | 30.8 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 30.8 mnt | val loss 0.4860 | acc 0.7834 P 0.7788 R 0.7840 F1 0.7814 macro-F1 0.7834
[R3_comment_roberta_lr2e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7834 | training 92.7 mnt | memori puncak 5.08 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 986.63it/s]

[R3_comment_distilbert_lr2e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6194 | lr 6.67e-06 | 1.6 mnt, sisa ±14.4 mnt
  epoch 1 |  4,997/24,984 | loss 0.5556 | lr 1.33e-05 | 3.2 mnt, sisa ±12.8 mnt
  epoch 1 |  7,496/24,984 | loss 0.5390 | lr 2.00e-05 | 4.8 mnt, sisa ±11.2 mnt
  epoch 1 |  9,994/24,984 | loss 0.5245 | lr 1.93e-05 | 6.4 mnt, sisa ±9.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5131 | lr 1.85e-05 | 8.0 mnt, sisa ±8.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.5126 | lr 1.78e-05 | 9.6 mnt, sisa ±6.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.5046 | lr 1.70e-05 | 11.2 mnt, sisa ±4.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.4990 | lr 1.63e-05 | 12.8 mnt, sisa ±3.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.4969 | lr 1.56e-05 | 14.4 mnt, sisa ±1.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4956 | lr 1.48e-05 | 16.0 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 16.0 mnt | val loss 0.5006 | acc 0.7583 P 0.7478 R 0.7702 F1 0.7589 macro-F1 0.7583
  epoch 2 |  2,499/24,984 | loss 0.4583 | lr 1.41e-05 | 1.6 mnt, sisa ±14.4 mnt
  epoch 2 |  4,997/24,984 | loss 0.4522 | lr 1.33e-05 | 3.2 mnt, sisa ±12.8 mnt
  epoch 2 |  7,496/24,984 | loss 0.4548 | lr 1.26e-05 | 4.8 mnt, sisa ±11.2 mnt
  epoch 2 |  9,994/24,984 | loss 0.4566 | lr 1.19e-05 | 6.4 mnt, sisa ±9.6 mnt
  epoch 2 | 12,492/24,984 | loss 0.4510 | lr 1.11e-05 | 8.0 mnt, sisa ±8.0 mnt
  epoch 2 | 14,991/24,984 | loss 0.4521 | lr 1.04e-05 | 9.6 mnt, sisa ±6.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4511 | lr 9.63e-06 | 11.2 mnt, sisa ±4.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4523 | lr 8.89e-06 | 12.8 mnt, sisa ±3.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4469 | lr 8.15e-06 | 14.4 mnt, sisa ±1.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4486 | lr 7.41e-06 | 16.0 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 16.0 mnt | val loss 0.4860 | acc 0.7681 P 0.7820 R 0.7354 F1 0.7580 macro-F1 0.7677
  epoch 3 |  2,499/24,984 | loss 0.3952 | lr 6.67e-06 | 1.6 mnt, sisa ±14.4 mnt
  epoch 3 |  4,997/24,984 | loss 0.3925 | lr 5.93e-06 | 3.2 mnt, sisa ±12.9 mnt
  epoch 3 |  7,496/24,984 | loss 0.3936 | lr 5.18e-06 | 4.9 mnt, sisa ±11.5 mnt
  epoch 3 |  9,994/24,984 | loss 0.3899 | lr 4.44e-06 | 6.5 mnt, sisa ±9.8 mnt
  epoch 3 | 12,492/24,984 | loss 0.3905 | lr 3.70e-06 | 8.1 mnt, sisa ±8.1 mnt
  epoch 3 | 14,991/24,984 | loss 0.3877 | lr 2.96e-06 | 9.7 mnt, sisa ±6.5 mnt
  epoch 3 | 17,489/24,984 | loss 0.3896 | lr 2.22e-06 | 11.3 mnt, sisa ±4.9 mnt
  epoch 3 | 19,988/24,984 | loss 0.3923 | lr 1.48e-06 | 12.9 mnt, sisa ±3.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.3886 | lr 7.41e-07 | 14.5 mnt, sisa ±1.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.3826 | lr 0.00e+00 | 16.1 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 16.1 mnt | val loss 0.5121 | acc 0.7654 P 0.7646 R 0.7586 F1 0.7615 macro-F1 0.7654
[R3_comment_distilbert_lr2e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7677 | training 48.1 mnt | memori puncak 2.63 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 906.93it/s]

[R3_comment_roberta_lr5e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 124.6 juta (dilatih 124.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.5904 | lr 1.67e-05 | 3.1 mnt, sisa ±27.7 mnt
  epoch 1 |  4,997/24,984 | loss 0.5392 | lr 3.33e-05 | 6.2 mnt, sisa ±24.6 mnt
  epoch 1 |  7,496/24,984 | loss 0.5407 | lr 5.00e-05 | 9.2 mnt, sisa ±21.5 mnt
  epoch 1 |  9,994/24,984 | loss 0.5314 | lr 4.81e-05 | 12.3 mnt, sisa ±18.5 mnt
  epoch 1 | 12,492/24,984 | loss 0.5274 | lr 4.63e-05 | 15.4 mnt, sisa ±15.4 mnt
  epoch 1 | 14,991/24,984 | loss 0.5271 | lr 4.44e-05 | 18.5 mnt, sisa ±12.3 mnt
  epoch 1 | 17,489/24,984 | loss 0.5325 | lr 4.26e-05 | 21.5 mnt, sisa ±9.2 mnt
  epoch 1 | 19,988/24,984 | loss 0.5316 | lr 4.07e-05 | 24.6 mnt, sisa ±6.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.5731 | lr 3.89e-05 | 27.7 mnt, sisa ±3.1 mnt
  epoch 1 | 24,984/24,984 | loss 0.5733 | lr 3.70e-05 | 30.8 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 30.8 mnt | val loss 0.5509 | acc 0.7383 P 0.8016 R 0.6247 F1 0.7022 macro-F1 0.7344
  epoch 2 |  2,499/24,984 | loss 0.5189 | lr 3.52e-05 | 3.1 mnt, sisa ±28.3 mnt
  epoch 2 |  4,997/24,984 | loss 0.5275 | lr 3.33e-05 | 6.3 mnt, sisa ±25.0 mnt
  epoch 2 |  7,496/24,984 | loss 0.5426 | lr 3.15e-05 | 9.4 mnt, sisa ±21.8 mnt
  epoch 2 |  9,994/24,984 | loss 0.5267 | lr 2.96e-05 | 12.4 mnt, sisa ±18.7 mnt
  epoch 2 | 12,492/24,984 | loss 0.5011 | lr 2.78e-05 | 15.6 mnt, sisa ±15.6 mnt
  epoch 2 | 14,991/24,984 | loss 0.5036 | lr 2.59e-05 | 18.7 mnt, sisa ±12.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.5017 | lr 2.41e-05 | 21.8 mnt, sisa ±9.3 mnt
  epoch 2 | 19,988/24,984 | loss 0.4995 | lr 2.22e-05 | 24.9 mnt, sisa ±6.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4893 | lr 2.04e-05 | 28.0 mnt, sisa ±3.1 mnt
  epoch 2 | 24,984/24,984 | loss 0.4880 | lr 1.85e-05 | 31.1 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 31.1 mnt | val loss 0.4962 | acc 0.7632 P 0.7680 R 0.7457 F1 0.7567 macro-F1 0.7630
  epoch 3 |  2,499/24,984 | loss 0.4670 | lr 1.67e-05 | 3.1 mnt, sisa ±28.2 mnt
  epoch 3 |  4,997/24,984 | loss 0.4652 | lr 1.48e-05 | 6.2 mnt, sisa ±24.9 mnt
  epoch 3 |  7,496/24,984 | loss 0.4604 | lr 1.30e-05 | 9.3 mnt, sisa ±21.7 mnt
  epoch 3 |  9,994/24,984 | loss 0.4566 | lr 1.11e-05 | 12.6 mnt, sisa ±18.9 mnt
  epoch 3 | 12,492/24,984 | loss 0.4578 | lr 9.26e-06 | 15.7 mnt, sisa ±15.7 mnt
  epoch 3 | 14,991/24,984 | loss 0.4540 | lr 7.41e-06 | 19.1 mnt, sisa ±12.7 mnt
  epoch 3 | 17,489/24,984 | loss 0.4508 | lr 5.56e-06 | 22.5 mnt, sisa ±9.7 mnt
  epoch 3 | 19,988/24,984 | loss 0.4515 | lr 3.70e-06 | 26.0 mnt, sisa ±6.5 mnt
  epoch 3 | 22,486/24,984 | loss 0.4500 | lr 1.85e-06 | 29.4 mnt, sisa ±3.3 mnt
  epoch 3 | 24,984/24,984 | loss 0.4482 | lr 0.00e+00 | 32.9 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 32.9 mnt | val loss 0.4889 | acc 0.7698 P 0.7723 R 0.7570 F1 0.7646 macro-F1 0.7697
[R3_comment_roberta_lr5e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7697 | training 94.8 mnt | memori puncak 5.08 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 698.06it/s]

[R3_comment_distilbert_lr5e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 65.8 juta (dilatih 65.8 juta)
  epoch 1 |  2,499/24,984 | loss 0.6000 | lr 1.67e-05 | 1.7 mnt, sisa ±15.2 mnt
  epoch 1 |  4,997/24,984 | loss 0.5496 | lr 3.33e-05 | 3.3 mnt, sisa ±13.2 mnt
  epoch 1 |  7,496/24,984 | loss 0.5381 | lr 5.00e-05 | 4.9 mnt, sisa ±11.5 mnt
  epoch 1 |  9,994/24,984 | loss 0.5294 | lr 4.81e-05 | 6.5 mnt, sisa ±9.8 mnt
  epoch 1 | 12,492/24,984 | loss 0.5184 | lr 4.63e-05 | 8.1 mnt, sisa ±8.1 mnt
  epoch 1 | 14,991/24,984 | loss 0.5182 | lr 4.44e-05 | 9.8 mnt, sisa ±6.5 mnt
  epoch 1 | 17,489/24,984 | loss 0.5110 | lr 4.26e-05 | 11.4 mnt, sisa ±4.9 mnt
  epoch 1 | 19,988/24,984 | loss 0.5068 | lr 4.07e-05 | 13.0 mnt, sisa ±3.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.5041 | lr 3.89e-05 | 14.6 mnt, sisa ±1.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.5017 | lr 3.70e-05 | 16.3 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 16.3 mnt | val loss 0.5133 | acc 0.7546 P 0.7444 R 0.7661 F1 0.7551 macro-F1 0.7546
  epoch 2 |  2,499/24,984 | loss 0.4581 | lr 3.52e-05 | 1.6 mnt, sisa ±14.6 mnt
  epoch 2 |  4,997/24,984 | loss 0.4529 | lr 3.33e-05 | 3.3 mnt, sisa ±13.1 mnt
  epoch 2 |  7,496/24,984 | loss 0.4567 | lr 3.15e-05 | 4.9 mnt, sisa ±11.4 mnt
  epoch 2 |  9,994/24,984 | loss 0.4596 | lr 2.96e-05 | 6.5 mnt, sisa ±9.7 mnt
  epoch 2 | 12,492/24,984 | loss 0.4533 | lr 2.78e-05 | 8.1 mnt, sisa ±8.1 mnt
  epoch 2 | 14,991/24,984 | loss 0.4552 | lr 2.59e-05 | 9.7 mnt, sisa ±6.5 mnt
  epoch 2 | 17,489/24,984 | loss 0.4538 | lr 2.41e-05 | 11.3 mnt, sisa ±4.9 mnt
  epoch 2 | 19,988/24,984 | loss 0.4541 | lr 2.22e-05 | 13.0 mnt, sisa ±3.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4498 | lr 2.04e-05 | 14.7 mnt, sisa ±1.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4497 | lr 1.85e-05 | 16.3 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 16.3 mnt | val loss 0.4939 | acc 0.7662 P 0.7807 R 0.7323 F1 0.7557 macro-F1 0.7658
  epoch 3 |  2,499/24,984 | loss 0.3696 | lr 1.67e-05 | 1.7 mnt, sisa ±14.9 mnt
  epoch 3 |  4,997/24,984 | loss 0.3665 | lr 1.48e-05 | 3.3 mnt, sisa ±13.1 mnt
  epoch 3 |  7,496/24,984 | loss 0.3677 | lr 1.30e-05 | 4.9 mnt, sisa ±11.5 mnt
  epoch 3 |  9,994/24,984 | loss 0.3619 | lr 1.11e-05 | 6.5 mnt, sisa ±9.8 mnt
  epoch 3 | 12,492/24,984 | loss 0.3629 | lr 9.26e-06 | 8.2 mnt, sisa ±8.2 mnt
  epoch 3 | 14,991/24,984 | loss 0.3598 | lr 7.41e-06 | 9.8 mnt, sisa ±6.5 mnt
  epoch 3 | 17,489/24,984 | loss 0.3607 | lr 5.56e-06 | 11.4 mnt, sisa ±4.9 mnt
  epoch 3 | 19,988/24,984 | loss 0.3614 | lr 3.70e-06 | 13.0 mnt, sisa ±3.3 mnt
  epoch 3 | 22,486/24,984 | loss 0.3602 | lr 1.85e-06 | 14.6 mnt, sisa ±1.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.3535 | lr 0.00e+00 | 16.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 16.2 mnt | val loss 0.5399 | acc 0.7599 P 0.7587 R 0.7535 F1 0.7561 macro-F1 0.7599
[R3_comment_distilbert_lr5e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7658 | training 48.8 mnt | memori puncak 2.63 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 884.45it/s]

[R3_late_roberta_lr1e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 127.0 juta (dilatih 127.0 juta)
  epoch 1 |  2,499/24,984 | loss 0.6410 | lr 3.33e-06 | 5.1 mnt, sisa ±45.7 mnt
  epoch 1 |  4,997/24,984 | loss 0.5479 | lr 6.67e-06 | 10.2 mnt, sisa ±40.6 mnt
  epoch 1 |  7,496/24,984 | loss 0.5241 | lr 1.00e-05 | 15.2 mnt, sisa ±35.5 mnt
  epoch 1 |  9,994/24,984 | loss 0.5116 | lr 9.63e-06 | 20.3 mnt, sisa ±30.4 mnt
  epoch 1 | 12,492/24,984 | loss 0.4988 | lr 9.26e-06 | 25.3 mnt, sisa ±25.3 mnt
  epoch 1 | 14,991/24,984 | loss 0.4871 | lr 8.89e-06 | 30.3 mnt, sisa ±20.2 mnt
  epoch 1 | 17,489/24,984 | loss 0.4871 | lr 8.52e-06 | 35.3 mnt, sisa ±15.1 mnt
  epoch 1 | 19,988/24,984 | loss 0.4790 | lr 8.15e-06 | 40.4 mnt, sisa ±10.1 mnt
  epoch 1 | 22,486/24,984 | loss 0.4748 | lr 7.78e-06 | 45.5 mnt, sisa ±5.1 mnt
  epoch 1 | 24,984/24,984 | loss 0.4741 | lr 7.41e-06 | 50.5 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 50.5 mnt | val loss 0.4645 | acc 0.7813 P 0.7754 R 0.7843 F1 0.7798 macro-F1 0.7813
  epoch 2 |  2,499/24,984 | loss 0.4456 | lr 7.04e-06 | 5.1 mnt, sisa ±45.5 mnt
  epoch 2 |  4,997/24,984 | loss 0.4447 | lr 6.67e-06 | 10.1 mnt, sisa ±40.5 mnt
  epoch 2 |  7,496/24,984 | loss 0.4436 | lr 6.30e-06 | 15.1 mnt, sisa ±35.3 mnt
  epoch 2 |  9,994/24,984 | loss 0.4429 | lr 5.93e-06 | 20.2 mnt, sisa ±30.3 mnt
  epoch 2 | 12,492/24,984 | loss 0.4413 | lr 5.56e-06 | 25.2 mnt, sisa ±25.2 mnt
  epoch 2 | 14,991/24,984 | loss 0.4381 | lr 5.19e-06 | 30.3 mnt, sisa ±20.2 mnt
  epoch 2 | 17,489/24,984 | loss 0.4398 | lr 4.81e-06 | 35.3 mnt, sisa ±15.1 mnt
  epoch 2 | 19,988/24,984 | loss 0.4384 | lr 4.44e-06 | 40.3 mnt, sisa ±10.1 mnt
  epoch 2 | 22,486/24,984 | loss 0.4338 | lr 4.07e-06 | 45.4 mnt, sisa ±5.0 mnt
  epoch 2 | 24,984/24,984 | loss 0.4348 | lr 3.70e-06 | 50.4 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 50.4 mnt | val loss 0.4537 | acc 0.7910 P 0.8006 R 0.7682 F1 0.7840 macro-F1 0.7908
  epoch 3 |  2,499/24,984 | loss 0.4055 | lr 3.33e-06 | 5.1 mnt, sisa ±45.7 mnt
  epoch 3 |  4,997/24,984 | loss 0.4006 | lr 2.96e-06 | 10.1 mnt, sisa ±40.5 mnt
  epoch 3 |  7,496/24,984 | loss 0.4026 | lr 2.59e-06 | 15.2 mnt, sisa ±35.4 mnt
  epoch 3 |  9,994/24,984 | loss 0.3997 | lr 2.22e-06 | 20.2 mnt, sisa ±30.3 mnt
  epoch 3 | 12,492/24,984 | loss 0.4008 | lr 1.85e-06 | 25.3 mnt, sisa ±25.3 mnt
  epoch 3 | 14,991/24,984 | loss 0.4009 | lr 1.48e-06 | 30.3 mnt, sisa ±20.2 mnt
  epoch 3 | 17,489/24,984 | loss 0.3958 | lr 1.11e-06 | 35.4 mnt, sisa ±15.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.3990 | lr 7.41e-07 | 40.4 mnt, sisa ±10.1 mnt
  epoch 3 | 22,486/24,984 | loss 0.3993 | lr 3.70e-07 | 45.4 mnt, sisa ±5.0 mnt
  epoch 3 | 24,984/24,984 | loss 0.3982 | lr 0.00e+00 | 50.4 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 50.4 mnt | val loss 0.4614 | acc 0.7918 P 0.7841 R 0.7982 F1 0.7911 macro-F1 0.7918
[R3_late_roberta_lr1e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7918 | training 151.3 mnt | memori puncak 8.38 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1155.96it/s]

[R3_late_distilbert_lr1e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 67.6 juta (dilatih 67.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6517 | lr 3.33e-06 | 2.6 mnt, sisa ±23.6 mnt
  epoch 1 |  4,997/24,984 | loss 0.5642 | lr 6.67e-06 | 5.2 mnt, sisa ±21.0 mnt
  epoch 1 |  7,496/24,984 | loss 0.5400 | lr 1.00e-05 | 7.8 mnt, sisa ±18.3 mnt
  epoch 1 |  9,994/24,984 | loss 0.5286 | lr 9.63e-06 | 10.4 mnt, sisa ±15.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5142 | lr 9.26e-06 | 13.0 mnt, sisa ±13.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.5055 | lr 8.89e-06 | 15.6 mnt, sisa ±10.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.5021 | lr 8.52e-06 | 18.2 mnt, sisa ±7.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.4991 | lr 8.15e-06 | 20.8 mnt, sisa ±5.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.4954 | lr 7.78e-06 | 23.4 mnt, sisa ±2.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4925 | lr 7.41e-06 | 26.0 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 26.0 mnt | val loss 0.4830 | acc 0.7656 P 0.7844 R 0.7244 F1 0.7532 macro-F1 0.7650
  epoch 2 |  2,499/24,984 | loss 0.4614 | lr 7.04e-06 | 2.6 mnt, sisa ±23.4 mnt
  epoch 2 |  4,997/24,984 | loss 0.4602 | lr 6.67e-06 | 5.2 mnt, sisa ±20.8 mnt
  epoch 2 |  7,496/24,984 | loss 0.4607 | lr 6.30e-06 | 7.8 mnt, sisa ±18.1 mnt
  epoch 2 |  9,994/24,984 | loss 0.4582 | lr 5.93e-06 | 10.4 mnt, sisa ±15.6 mnt
  epoch 2 | 12,492/24,984 | loss 0.4542 | lr 5.56e-06 | 13.0 mnt, sisa ±13.0 mnt
  epoch 2 | 14,991/24,984 | loss 0.4559 | lr 5.19e-06 | 15.6 mnt, sisa ±10.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4540 | lr 4.81e-06 | 18.2 mnt, sisa ±7.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4556 | lr 4.44e-06 | 20.8 mnt, sisa ±5.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4493 | lr 4.07e-06 | 23.3 mnt, sisa ±2.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4525 | lr 3.70e-06 | 25.9 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 25.9 mnt | val loss 0.4728 | acc 0.7724 P 0.7677 R 0.7730 F1 0.7703 macro-F1 0.7724
  epoch 3 |  2,499/24,984 | loss 0.4161 | lr 3.33e-06 | 2.6 mnt, sisa ±23.4 mnt
  epoch 3 |  4,997/24,984 | loss 0.4172 | lr 2.96e-06 | 5.2 mnt, sisa ±20.7 mnt
  epoch 3 |  7,496/24,984 | loss 0.4163 | lr 2.59e-06 | 7.8 mnt, sisa ±18.2 mnt
  epoch 3 |  9,994/24,984 | loss 0.4146 | lr 2.22e-06 | 10.4 mnt, sisa ±15.6 mnt
  epoch 3 | 12,492/24,984 | loss 0.4150 | lr 1.85e-06 | 13.0 mnt, sisa ±13.0 mnt
  epoch 3 | 14,991/24,984 | loss 0.4154 | lr 1.48e-06 | 15.6 mnt, sisa ±10.4 mnt
  epoch 3 | 17,489/24,984 | loss 0.4145 | lr 1.11e-06 | 18.2 mnt, sisa ±7.8 mnt
  epoch 3 | 19,988/24,984 | loss 0.4181 | lr 7.41e-07 | 20.7 mnt, sisa ±5.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.4102 | lr 3.70e-07 | 23.3 mnt, sisa ±2.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.4111 | lr 0.00e+00 | 26.0 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 26.0 mnt | val loss 0.4786 | acc 0.7768 P 0.7782 R 0.7664 F1 0.7723 macro-F1 0.7767
[R3_late_distilbert_lr1e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7767 | training 77.8 mnt | memori puncak 4.29 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1248.27it/s]

[R3_late_roberta_lr2e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 127.0 juta (dilatih 127.0 juta)
  epoch 1 |  2,499/24,984 | loss 0.6165 | lr 6.67e-06 | 5.2 mnt, sisa ±47.0 mnt
  epoch 1 |  4,997/24,984 | loss 0.5388 | lr 1.33e-05 | 10.4 mnt, sisa ±41.6 mnt
  epoch 1 |  7,496/24,984 | loss 0.5214 | lr 2.00e-05 | 15.7 mnt, sisa ±36.5 mnt
  epoch 1 |  9,994/24,984 | loss 0.5110 | lr 1.93e-05 | 21.1 mnt, sisa ±31.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5009 | lr 1.85e-05 | 26.1 mnt, sisa ±26.1 mnt
  epoch 1 | 14,991/24,984 | loss 0.4892 | lr 1.78e-05 | 31.1 mnt, sisa ±20.7 mnt
  epoch 1 | 17,489/24,984 | loss 0.4893 | lr 1.70e-05 | 36.1 mnt, sisa ±15.5 mnt
  epoch 1 | 19,988/24,984 | loss 0.4799 | lr 1.63e-05 | 41.2 mnt, sisa ±10.3 mnt
  epoch 1 | 22,486/24,984 | loss 0.4755 | lr 1.56e-05 | 46.4 mnt, sisa ±5.2 mnt
  epoch 1 | 24,984/24,984 | loss 0.4756 | lr 1.48e-05 | 51.4 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 51.4 mnt | val loss 0.4644 | acc 0.7794 P 0.7710 R 0.7871 F1 0.7790 macro-F1 0.7794
  epoch 2 |  2,499/24,984 | loss 0.4394 | lr 1.41e-05 | 5.1 mnt, sisa ±45.6 mnt
  epoch 2 |  4,997/24,984 | loss 0.4402 | lr 1.33e-05 | 10.1 mnt, sisa ±40.5 mnt
  epoch 2 |  7,496/24,984 | loss 0.4383 | lr 1.26e-05 | 15.2 mnt, sisa ±35.4 mnt
  epoch 2 |  9,994/24,984 | loss 0.4377 | lr 1.19e-05 | 20.2 mnt, sisa ±30.3 mnt
  epoch 2 | 12,492/24,984 | loss 0.4356 | lr 1.11e-05 | 25.3 mnt, sisa ±25.3 mnt
  epoch 2 | 14,991/24,984 | loss 0.4328 | lr 1.04e-05 | 30.3 mnt, sisa ±20.2 mnt
  epoch 2 | 17,489/24,984 | loss 0.4347 | lr 9.63e-06 | 35.4 mnt, sisa ±15.2 mnt
  epoch 2 | 19,988/24,984 | loss 0.4330 | lr 8.89e-06 | 40.4 mnt, sisa ±10.1 mnt
  epoch 2 | 22,486/24,984 | loss 0.4285 | lr 8.15e-06 | 45.5 mnt, sisa ±5.0 mnt
  epoch 2 | 24,984/24,984 | loss 0.4277 | lr 7.41e-06 | 50.5 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 50.5 mnt | val loss 0.4577 | acc 0.7903 P 0.7955 R 0.7745 F1 0.7849 macro-F1 0.7902
  epoch 3 |  2,499/24,984 | loss 0.3866 | lr 6.67e-06 | 5.1 mnt, sisa ±45.5 mnt
  epoch 3 |  4,997/24,984 | loss 0.3816 | lr 5.93e-06 | 10.1 mnt, sisa ±40.4 mnt
  epoch 3 |  7,496/24,984 | loss 0.3814 | lr 5.18e-06 | 15.2 mnt, sisa ±35.4 mnt
  epoch 3 |  9,994/24,984 | loss 0.3797 | lr 4.44e-06 | 20.2 mnt, sisa ±30.3 mnt
  epoch 3 | 12,492/24,984 | loss 0.3788 | lr 3.70e-06 | 25.3 mnt, sisa ±25.3 mnt
  epoch 3 | 14,991/24,984 | loss 0.3793 | lr 2.96e-06 | 30.3 mnt, sisa ±20.2 mnt
  epoch 3 | 17,489/24,984 | loss 0.3746 | lr 2.22e-06 | 35.4 mnt, sisa ±15.2 mnt
  epoch 3 | 19,988/24,984 | loss 0.3770 | lr 1.48e-06 | 40.4 mnt, sisa ±10.1 mnt
  epoch 3 | 22,486/24,984 | loss 0.3776 | lr 7.41e-07 | 45.5 mnt, sisa ±5.1 mnt
  epoch 3 | 24,984/24,984 | loss 0.3765 | lr 0.00e+00 | 50.5 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 50.5 mnt | val loss 0.4704 | acc 0.7916 P 0.7827 R 0.8000 F1 0.7913 macro-F1 0.7916
[R3_late_roberta_lr2e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7916 | training 152.4 mnt | memori puncak 8.38 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1280.48it/s]

[R3_late_distilbert_lr2e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 67.6 juta (dilatih 67.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6292 | lr 6.67e-06 | 2.6 mnt, sisa ±23.5 mnt
  epoch 1 |  4,997/24,984 | loss 0.5525 | lr 1.33e-05 | 5.2 mnt, sisa ±20.9 mnt
  epoch 1 |  7,496/24,984 | loss 0.5336 | lr 2.00e-05 | 7.8 mnt, sisa ±18.3 mnt
  epoch 1 |  9,994/24,984 | loss 0.5235 | lr 1.93e-05 | 10.4 mnt, sisa ±15.7 mnt
  epoch 1 | 12,492/24,984 | loss 0.5090 | lr 1.85e-05 | 13.0 mnt, sisa ±13.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.5012 | lr 1.78e-05 | 15.7 mnt, sisa ±10.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.4970 | lr 1.70e-05 | 18.3 mnt, sisa ±7.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.4949 | lr 1.63e-05 | 20.9 mnt, sisa ±5.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.4912 | lr 1.56e-05 | 23.5 mnt, sisa ±2.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4881 | lr 1.48e-05 | 26.1 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 26.1 mnt | val loss 0.4812 | acc 0.7686 P 0.7862 R 0.7300 F1 0.7570 macro-F1 0.7681
  epoch 2 |  2,499/24,984 | loss 0.4442 | lr 1.41e-05 | 2.6 mnt, sisa ±23.5 mnt
  epoch 2 |  4,997/24,984 | loss 0.4443 | lr 1.33e-05 | 5.2 mnt, sisa ±20.9 mnt
  epoch 2 |  7,496/24,984 | loss 0.4444 | lr 1.26e-05 | 7.8 mnt, sisa ±18.3 mnt
  epoch 2 |  9,994/24,984 | loss 0.4430 | lr 1.19e-05 | 10.4 mnt, sisa ±15.6 mnt
  epoch 2 | 12,492/24,984 | loss 0.4391 | lr 1.11e-05 | 13.0 mnt, sisa ±13.0 mnt
  epoch 2 | 14,991/24,984 | loss 0.4403 | lr 1.04e-05 | 15.7 mnt, sisa ±10.4 mnt
  epoch 2 | 17,489/24,984 | loss 0.4381 | lr 9.63e-06 | 18.3 mnt, sisa ±7.8 mnt
  epoch 2 | 19,988/24,984 | loss 0.4406 | lr 8.89e-06 | 20.9 mnt, sisa ±5.2 mnt
  epoch 2 | 22,486/24,984 | loss 0.4334 | lr 8.15e-06 | 23.5 mnt, sisa ±2.6 mnt
  epoch 2 | 24,984/24,984 | loss 0.4363 | lr 7.41e-06 | 26.1 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 26.1 mnt | val loss 0.4701 | acc 0.7760 P 0.7724 R 0.7745 F1 0.7735 macro-F1 0.7759
  epoch 3 |  2,499/24,984 | loss 0.3759 | lr 6.67e-06 | 2.6 mnt, sisa ±23.5 mnt
  epoch 3 |  4,997/24,984 | loss 0.3751 | lr 5.93e-06 | 5.2 mnt, sisa ±20.8 mnt
  epoch 3 |  7,496/24,984 | loss 0.3751 | lr 5.18e-06 | 7.8 mnt, sisa ±18.3 mnt
  epoch 3 |  9,994/24,984 | loss 0.3710 | lr 4.44e-06 | 10.4 mnt, sisa ±15.7 mnt
  epoch 3 | 12,492/24,984 | loss 0.3709 | lr 3.70e-06 | 13.0 mnt, sisa ±13.0 mnt
  epoch 3 | 14,991/24,984 | loss 0.3705 | lr 2.96e-06 | 15.7 mnt, sisa ±10.4 mnt
  epoch 3 | 17,489/24,984 | loss 0.3731 | lr 2.22e-06 | 18.3 mnt, sisa ±7.8 mnt
  epoch 3 | 19,988/24,984 | loss 0.3723 | lr 1.48e-06 | 20.9 mnt, sisa ±5.2 mnt
  epoch 3 | 22,486/24,984 | loss 0.3665 | lr 7.41e-07 | 23.5 mnt, sisa ±2.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.3672 | lr 0.00e+00 | 26.1 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 26.1 mnt | val loss 0.4970 | acc 0.7759 P 0.7743 R 0.7708 F1 0.7725 macro-F1 0.7758
[R3_late_distilbert_lr2e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7759 | training 78.3 mnt | memori puncak 4.29 GB

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 875.43it/s]

[R3_late_roberta_lr5e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 127.0 juta (dilatih 127.0 juta)
  epoch 1 |  2,499/24,984 | loss 0.5937 | lr 1.67e-05 | 5.1 mnt, sisa ±45.7 mnt
  epoch 1 |  4,997/24,984 | loss 0.5394 | lr 3.33e-05 | 10.1 mnt, sisa ±40.5 mnt
  epoch 1 |  7,496/24,984 | loss 0.5322 | lr 5.00e-05 | 15.2 mnt, sisa ±35.4 mnt
  epoch 1 |  9,994/24,984 | loss 0.5327 | lr 4.81e-05 | 20.2 mnt, sisa ±30.3 mnt
  epoch 1 | 12,492/24,984 | loss 0.5212 | lr 4.63e-05 | 25.3 mnt, sisa ±25.3 mnt
  epoch 1 | 14,991/24,984 | loss 0.5125 | lr 4.44e-05 | 30.3 mnt, sisa ±20.2 mnt
  epoch 1 | 17,489/24,984 | loss 0.5119 | lr 4.26e-05 | 35.4 mnt, sisa ±15.2 mnt
  epoch 1 | 19,988/24,984 | loss 0.5048 | lr 4.07e-05 | 40.4 mnt, sisa ±10.1 mnt
  epoch 1 | 22,486/24,984 | loss 0.4990 | lr 3.89e-05 | 45.5 mnt, sisa ±5.1 mnt
  epoch 1 | 24,984/24,984 | loss 0.5054 | lr 3.70e-05 | 50.6 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 50.6 mnt | val loss 0.4919 | acc 0.7640 P 0.7538 R 0.7751 F1 0.7643 macro-F1 0.7640
  epoch 2 |  2,499/24,984 | loss 0.4716 | lr 3.52e-05 | 5.1 mnt, sisa ±45.7 mnt
  epoch 2 |  4,997/24,984 | loss 0.4706 | lr 3.33e-05 | 10.2 mnt, sisa ±40.6 mnt
  epoch 2 |  7,496/24,984 | loss 0.4684 | lr 3.15e-05 | 15.2 mnt, sisa ±35.4 mnt
  epoch 2 |  9,994/24,984 | loss 0.4654 | lr 2.96e-05 | 20.3 mnt, sisa ±30.4 mnt
  epoch 2 | 12,492/24,984 | loss 0.4607 | lr 2.78e-05 | 25.3 mnt, sisa ±25.3 mnt
  epoch 2 | 14,991/24,984 | loss 0.4598 | lr 2.59e-05 | 30.4 mnt, sisa ±20.3 mnt
  epoch 2 | 17,489/24,984 | loss 0.4583 | lr 2.41e-05 | 35.4 mnt, sisa ±15.2 mnt
  epoch 2 | 19,988/24,984 | loss 0.4554 | lr 2.22e-05 | 40.5 mnt, sisa ±10.1 mnt
  epoch 2 | 22,486/24,984 | loss 0.4527 | lr 2.04e-05 | 45.5 mnt, sisa ±5.1 mnt
  epoch 2 | 24,984/24,984 | loss 0.4512 | lr 1.85e-05 | 50.7 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 50.7 mnt | val loss 0.4748 | acc 0.7798 P 0.7876 R 0.7587 F1 0.7729 macro-F1 0.7796
  epoch 3 |  2,499/24,984 | loss 0.4090 | lr 1.67e-05 | 5.2 mnt, sisa ±47.2 mnt
  epoch 3 |  4,997/24,984 | loss 0.4026 | lr 1.48e-05 | 10.5 mnt, sisa ±42.0 mnt
  epoch 3 |  7,496/24,984 | loss 0.4002 | lr 1.30e-05 | 15.6 mnt, sisa ±36.4 mnt
  epoch 3 |  9,994/24,984 | loss 0.3981 | lr 1.11e-05 | 21.0 mnt, sisa ±31.6 mnt
  epoch 3 | 12,492/24,984 | loss 0.3961 | lr 9.26e-06 | 26.4 mnt, sisa ±26.4 mnt
  epoch 3 | 14,991/24,984 | loss 0.3988 | lr 7.41e-06 | 31.7 mnt, sisa ±21.2 mnt
  epoch 3 | 17,489/24,984 | loss 0.3942 | lr 5.56e-06 | 37.0 mnt, sisa ±15.9 mnt
  epoch 3 | 19,988/24,984 | loss 0.3932 | lr 3.70e-06 | 42.2 mnt, sisa ±10.6 mnt
  epoch 3 | 22,486/24,984 | loss 0.3939 | lr 1.85e-06 | 47.4 mnt, sisa ±5.3 mnt
  epoch 3 | 24,984/24,984 | loss 0.3918 | lr 0.00e+00 | 52.4 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 52.4 mnt | val loss 0.4798 | acc 0.7826 P 0.7721 R 0.7940 F1 0.7829 macro-F1 0.7826
[R3_late_roberta_lr5e-05_s42] SELESAI | epoch terbaik 3 | val macro_f1 0.7826 | training 153.7 mnt | memori puncak 8.38 GB

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 809.40it/s]

[R3_late_distilbert_lr5e-05_s42] train 799,459 | val 100,276 | 24,984 langkah/epoch | parameter 67.6 juta (dilatih 67.6 juta)
  epoch 1 |  2,499/24,984 | loss 0.6069 | lr 1.67e-05 | 2.6 mnt, sisa ±23.6 mnt
  epoch 1 |  4,997/24,984 | loss 0.5469 | lr 3.33e-05 | 5.2 mnt, sisa ±20.9 mnt
  epoch 1 |  7,496/24,984 | loss 0.5345 | lr 5.00e-05 | 7.8 mnt, sisa ±18.3 mnt
  epoch 1 |  9,994/24,984 | loss 0.5294 | lr 4.81e-05 | 10.4 mnt, sisa ±15.6 mnt
  epoch 1 | 12,492/24,984 | loss 0.5158 | lr 4.63e-05 | 13.0 mnt, sisa ±13.0 mnt
  epoch 1 | 14,991/24,984 | loss 0.5092 | lr 4.44e-05 | 15.6 mnt, sisa ±10.4 mnt
  epoch 1 | 17,489/24,984 | loss 0.5052 | lr 4.26e-05 | 18.2 mnt, sisa ±7.8 mnt
  epoch 1 | 19,988/24,984 | loss 0.5031 | lr 4.07e-05 | 20.9 mnt, sisa ±5.2 mnt
  epoch 1 | 22,486/24,984 | loss 0.5001 | lr 3.89e-05 | 23.5 mnt, sisa ±2.6 mnt
  epoch 1 | 24,984/24,984 | loss 0.4964 | lr 3.70e-05 | 26.2 mnt, sisa ±0.0 mnt
  epoch 1 selesai | train 26.2 mnt | val loss 0.4922 | acc 0.7651 P 0.7910 R 0.7125 F1 0.7497 macro-F1 0.7642
  epoch 2 |  2,499/24,984 | loss 0.4480 | lr 3.52e-05 | 2.7 mnt, sisa ±24.2 mnt
  epoch 2 |  4,997/24,984 | loss 0.4472 | lr 3.33e-05 | 5.4 mnt, sisa ±21.6 mnt
  epoch 2 |  7,496/24,984 | loss 0.4487 | lr 3.15e-05 | 8.1 mnt, sisa ±18.9 mnt
  epoch 2 |  9,994/24,984 | loss 0.4480 | lr 2.96e-05 | 10.8 mnt, sisa ±16.3 mnt
  epoch 2 | 12,492/24,984 | loss 0.4430 | lr 2.78e-05 | 13.5 mnt, sisa ±13.5 mnt
  epoch 2 | 14,991/24,984 | loss 0.4441 | lr 2.59e-05 | 16.2 mnt, sisa ±10.8 mnt
  epoch 2 | 17,489/24,984 | loss 0.4424 | lr 2.41e-05 | 19.1 mnt, sisa ±8.2 mnt
  epoch 2 | 19,988/24,984 | loss 0.4441 | lr 2.22e-05 | 21.8 mnt, sisa ±5.4 mnt
  epoch 2 | 22,486/24,984 | loss 0.4362 | lr 2.04e-05 | 24.5 mnt, sisa ±2.7 mnt
  epoch 2 | 24,984/24,984 | loss 0.4389 | lr 1.85e-05 | 27.2 mnt, sisa ±0.0 mnt
  epoch 2 selesai | train 27.2 mnt | val loss 0.4805 | acc 0.7707 P 0.7614 R 0.7801 F1 0.7706 macro-F1 0.7707
  epoch 3 |  2,499/24,984 | loss 0.3507 | lr 1.67e-05 | 2.7 mnt, sisa ±24.0 mnt
  epoch 3 |  4,997/24,984 | loss 0.3506 | lr 1.48e-05 | 5.3 mnt, sisa ±21.1 mnt
  epoch 3 |  7,496/24,984 | loss 0.3495 | lr 1.30e-05 | 7.9 mnt, sisa ±18.5 mnt
  epoch 3 |  9,994/24,984 | loss 0.3462 | lr 1.11e-05 | 10.5 mnt, sisa ±15.8 mnt
  epoch 3 | 12,492/24,984 | loss 0.3451 | lr 9.26e-06 | 13.1 mnt, sisa ±13.1 mnt
  epoch 3 | 14,991/24,984 | loss 0.3447 | lr 7.41e-06 | 15.7 mnt, sisa ±10.5 mnt
  epoch 3 | 17,489/24,984 | loss 0.3447 | lr 5.56e-06 | 18.4 mnt, sisa ±7.9 mnt
  epoch 3 | 19,988/24,984 | loss 0.3446 | lr 3.70e-06 | 21.0 mnt, sisa ±5.3 mnt
  epoch 3 | 22,486/24,984 | loss 0.3375 | lr 1.85e-06 | 23.6 mnt, sisa ±2.6 mnt
  epoch 3 | 24,984/24,984 | loss 0.3368 | lr 0.00e+00 | 26.2 mnt, sisa ±0.0 mnt
  epoch 3 selesai | train 26.2 mnt | val loss 0.5263 | acc 0.7690 P 0.7664 R 0.7655 F1 0.7660 macro-F1 0.7690
[R3_late_distilbert_lr5e-05_s42] SELESAI | epoch terbaik 2 | val macro_f1 0.7707 | training 79.6 mnt | memori puncak 4.28 GB

#### Insight
Semua 24 run selesai tanpa error. Training berjalan dari 7 Oktober sore sampai 9 Oktober pagi, sekitar 36 jam tanpa berhenti.

Satu epoch RoBERTa butuh sekitar 31 menit untuk comment saja, 33 menit untuk early fusion, dan 50 menit untuk late fusion. DistilBERT kira-kira setengahnya, yaitu 16, 17, dan 26 menit.

Di bagian awal setiap run, learning rate naik pelan-pelan selama warmup sampai mencapai nilai yang ditentukan, lalu turun sampai 0 di akhir epoch 3. Loss latih juga turun dari epoch ke epoch di semua run, jadi model memang belajar.

Ada dua pola yang terlihat dari log di atas:
1. Learning rate 5e-5 terlalu besar untuk RoBERTa. Pada RoBERTa comment saja dengan learning rate 5e-5, learning rate mencapai puncaknya (5e-5) di sekitar 30% epoch pertama. Setelah itu loss tidak lagi turun dengan baik. Loss sempat berada di 0,527, lalu menjelang akhir epoch 1 malah naik menjadi 0,573. Model seperti "terlempar" karena langkah belajarnya terlalu besar. Pada learning rate yang lebih kecil, loss terus turun dengan mulus.
2. Learning rate yang lebih besar membuat model lebih cepat overfitting. Contohnya DistilBERT early fusion dengan learning rate 5e-5, loss validasi turun di epoch 2 lalu naik lagi di epoch 3 (0,478 menjadi 0,535). Artinya model mulai menghafal data latih. Sebaliknya dengan learning rate 1e-5, epoch terbaik selalu epoch 3, jadi model masih bisa belajar sampai akhir.

## 4. Hasil

Tabel berisi hasil validasi di epoch terbaik untuk setiap run, beserta angka efisiensinya.

Keterangan kolom:
- `val_accuracy`, `val_precision`, `val_recall`, `val_f1`, `val_macro_f1`: nilai di data validasi,
- `train_min_total`: lama training 3 epoch dalam menit (tanpa waktu evaluasi),
- `peak_mem_gb`: memori GPU tertinggi saat training,
- `latency_bs1_ms`: waktu menebak 1 data dalam milidetik kalau data diproses satu per satu,
- `latency_bs32_ms`: waktu menebak per data kalau 32 data diproses sekaligus.

Selisih nilai di bawah ditulis dalam poin, misalnya 0,7962 dan 0,7834 berselisih 1,28 poin.

In [4]:
runs = pd.read_csv(OUT_DIR / "runs.csv")
cols = ["run_id", "best_epoch", "val_accuracy", "val_precision", "val_recall", "val_f1", "val_macro_f1",
        "train_min_total", "peak_mem_gb", "latency_bs1_ms", "latency_bs32_ms"]
display(runs[cols].round(4))

,run_id,best_epoch,val_accuracy,val_precision,val_recall,val_f1,val_macro_f1,train_min_total,peak_mem_gb,latency_bs1_ms,latency_bs32_ms
0,R1_comment_roberta_lr3e-05_s42,3,0.7808,0.7772,0.7796,0.7784,0.7808,92.0666,5.0840,15.9276,0.5641
1,R1_comment_distilbert_lr3e-05_s42,2,0.7669,0.7760,0.7423,0.7588,0.7667,48.1486,2.6316,7.7130,0.2793
2,R1_early_roberta_lr3e-05_s42,2,0.7927,0.7994,0.7747,0.7868,0.7926,100.0666,5.1063,15.3514,1.1613
3,R1_early_distilbert_lr3e-05_s42,2,0.7742,0.7654,0.7825,0.7738,0.7742,52.4548,2.6395,7.6691,0.6115
4,R1_late_roberta_lr3e-05_s42,3,0.7893,0.7782,0.8019,0.7899,0.7893,150.2840,8.3798,27.3933,1.5393
5,R1_late_distilbert_lr3e-05_s42,2,0.7756,0.7703,0.7772,0.7738,0.7755,77.5088,4.2835,13.3500,0.8019
6,R2_early_roberta_lr1e-05_s42,3,0.7962,0.7850,0.8087,0.7967,0.7962,99.5151,5.1063,15.3495,1.1636
7,R2_early_distilbert_lr1e-05_s42,3,0.7732,0.7714,0.7683,0.7699,0.7731,51.8788,2.6395,7.6400,0.6078
8,R2_early_roberta_lr2e-05_s42,2,0.7951,0.7972,0.7847,0.7909,0.7950,99.3562,5.1054,15.1696,1.1605
9,R2_early_distilbert_lr2e-05_s42,3,0.7745,0.7705,0.7737,0.7721,0.7744,51.9789,2.6395,7.4610,0.6067
10,R2_early_roberta_lr5e-05_s42,3,0.7854,0.7755,0.7957,0.7855,0.7854,98.6268,5.1054,15.2876,1.1621
11,R2_early_distilbert_lr5e-05_s42,2,0.7715,0.7639,0.7776,0.7707,0.7715,52.1266,2.6395,7.9986,0.6755
12,R3_comment_roberta_lr1e-05_s42,3,0.7827,0.7796,0.7808,0.7802,0.7827,93.4114,5.0847,15.3543,0.5434
13,R3_comment_distilbert_lr1e-05_s42,3,0.7673,0.7687,0.7562,0.7624,0.7672,47.9967,2.6322,7.7695,0.2822
14,R3_comment_roberta_lr2e-05_s42,3,0.7834,0.7788,0.7840,0.7814,0.7834,92.7384,5.0847,15.3153,0.5428
15,R3_comment_distilbert_lr2e-05_s42,2,0.7681,0.7820,0.7354,0.7580,0.7677,48.0653,2.6322,7.6887,0.2826
16,R3_comment_roberta_lr5e-05_s42,3,0.7698,0.7723,0.7570,0.7646,0.7697,94.8172,5.0847,17.4778,0.6129
17,R3_comment_distilbert_lr5e-05_s42,2,0.7662,0.7807,0.7323,0.7557,0.7658,48.7840,2.6322,7.8115,0.2869
18,R3_late_roberta_lr1e-05_s42,3,0.7918,0.7841,0.7982,0.7911,0.7918,151.3216,8.3798,27.5616,1.5421
19,R3_late_distilbert_lr1e-05_s42,3,0.7768,0.7782,0.7664,0.7723,0.7767,77.8448,4.2873,13.3506,0.8521
20,R3_late_roberta_lr2e-05_s42,3,0.7916,0.7827,0.8000,0.7913,0.7916,152.4294,8.3798,27.5738,1.5365
21,R3_late_distilbert_lr2e-05_s42,2,0.7760,0.7724,0.7745,0.7735,0.7759,78.2648,4.2873,13.4580,0.8026
22,R3_late_roberta_lr5e-05_s42,3,0.7826,0.7721,0.7940,0.7829,0.7826,153.7140,8.3798,27.6728,1.5471
23,R3_late_distilbert_lr5e-05_s42,2,0.7707,0.7614,0.7801,0.7706,0.7707,79.5887,4.2835,13.4737,0.8091

#### Insight: pengaruh learning rate

Macro-F1 validasi untuk setiap learning rate:

| Input | Model | 1e-5 | 2e-5 | 3e-5 | 5e-5 |
|---|---|---:|---:|---:|---:|
| Comment saja | RoBERTa | 0,7827 | 0,7834 | 0,7808 | 0,7697 |
| Comment saja | DistilBERT | 0,7672 | 0,7677 | 0,7667 | 0,7658 |
| Early fusion | RoBERTa | 0,7962 | 0,7950 | 0,7926 | 0,7854 |
| Early fusion | DistilBERT | 0,7731 | 0,7744 | 0,7742 | 0,7715 |
| Late fusion | RoBERTa | 0,7918 | 0,7916 | 0,7893 | 0,7826 |
| Late fusion | DistilBERT | 0,7767 | 0,7759 | 0,7755 | 0,7707 |

RoBERTa lebih cocok dengan learning rate kecil. Learning rate 1e-5 dan 2e-5 hasilnya hampir sama dan selalu yang terbaik, sedangkan 5e-5 selalu paling rendah, sekitar 1 sampai 1,4 poin di bawah yang terbaik. Ini sesuai dengan loss yang naik lagi pada learning rate 5e-5 di bagian 3.

DistilBERT hampir tidak terpengaruh learning rate. Selisih antara hasil terbaik dan terburuk hanya 0,2 sampai 0,6 poin.

Learning rate 3e-5 yang dulu terpilih di pilot lama (data 40.000) ternyata bukan yang terbaik untuk data penuh, terutama untuk RoBERTa. Jadi learning rate yang cocok untuk data kecil belum tentu cocok untuk data besar.

#### Insight: hasil terbaik setiap konfigurasi

Learning rate terbaik dipilih dari macro-F1 validasi tertinggi:

| Input | Model | Learning rate | Accuracy | Precision | Recall | F1 | Macro-F1 |
|---|---|---|---:|---:|---:|---:|---:|
| Comment saja | RoBERTa | 2e-5 | 0,7834 | 0,7788 | 0,7840 | 0,7814 | 0,7834 |
| Comment saja | DistilBERT | 2e-5 | 0,7681 | 0,7820 | 0,7354 | 0,7580 | 0,7677 |
| Early fusion | RoBERTa | 1e-5 | 0,7962 | 0,7850 | 0,8087 | 0,7967 | 0,7962 |
| Early fusion | DistilBERT | 2e-5 | 0,7745 | 0,7705 | 0,7737 | 0,7721 | 0,7744 |
| Late fusion | RoBERTa | 1e-5 | 0,7918 | 0,7841 | 0,7982 | 0,7911 | 0,7918 |
| Late fusion | DistilBERT | 1e-5 | 0,7768 | 0,7782 | 0,7664 | 0,7723 | 0,7767 |

Hasil terbaik didapat RoBERTa dengan early fusion, yaitu F1 0,7967. Angka ini jauh di atas hasil percobaan sebelumnya dengan 40.000 data (F1 0,743). Kemungkinan karena data latih sekarang 20 kali lebih banyak, dan huruf kapital serta tanda baca tidak lagi dihapus.

Precision dan recall di semua konfigurasi cukup seimbang, sekitar 0,73 sampai 0,81, jadi model tidak berat sebelah ke salah satu kelas.

#### Insight: RoBERTa dibanding DistilBERT

Perbandingan pada learning rate 3e-5 (putaran 1), supaya kedua model dibandingkan dengan pengaturan yang sama:

| | Comment saja | Early fusion | Late fusion |
|---|---:|---:|---:|
| Waktu training 3 epoch (menit) RoBERTa / DistilBERT | 92 / 48 | 100 / 52 | 150 / 78 |
| DistilBERT lebih cepat training | 1,91× | 1,91× | 1,94× |
| Waktu menebak 1 data (ms) RoBERTa / DistilBERT | 15,9 / 7,7 | 15,4 / 7,7 | 27,4 / 13,4 |
| DistilBERT lebih cepat menebak | 2,07× | 2,00× | 2,05× |
| Memori (GB) RoBERTa / DistilBERT | 5,08 / 2,63 | 5,11 / 2,64 | 8,38 / 4,28 |

Dengan learning rate terbaik masing-masing, macro-F1 RoBERTa lebih tinggi 1,57 poin (comment saja), 2,18 poin (early fusion), dan 1,51 poin (late fusion) dibanding DistilBERT.

Jadi kalau memakai DistilBERT, performa turun sekitar 1,5 sampai 2,2 poin, tapi training dan prediksinya sekitar 2 kali lebih cepat dan memorinya sekitar setengah. Polanya sama di ketiga jenis input.

#### Insight: pengaruh konteks parent dan cara penggabungannya

Dengan learning rate terbaik masing-masing, menambahkan parent menaikkan macro-F1 dibanding comment saja:

| | RoBERTa | DistilBERT |
|---|---:|---:|
| Early fusion dibanding comment saja | +1,28 poin | +0,67 poin |
| Late fusion dibanding comment saja | +0,84 poin | +0,90 poin |

Pada data penuh, parent ternyata membantu, terutama untuk RoBERTa. Ini berbeda dengan percobaan sebelumnya dengan 40.000 data, yang selisihnya kurang dari 0,01. Kemungkinan dengan data yang lebih banyak, model bisa belajar memanfaatkan konteks.

Dari sisi waktu, early fusion hanya 1,09 kali lebih lama dari comment saja, padahal teksnya hampir tiga kali lebih panjang. Jadi menambahkan parent lewat early fusion hampir tidak menambah waktu training.

Late fusion tidak lebih baik dari early fusion. Pada RoBERTa hasilnya 0,44 poin lebih rendah, dan pada DistilBERT hanya 0,23 poin lebih tinggi. Padahal late fusion jauh lebih berat, yaitu training 1,5 kali lebih lama, menebak sekitar 1,75 kali lebih lambat, dan memori sekitar 1,6 kali lebih besar. Penyebabnya, late fusion menjalankan model dua kali, sekali untuk parent dan sekali untuk comment. Untuk data ini, early fusion adalah cara penggabungan yang lebih baik.

#### Catatan
Semua hasil ini berasal dari satu seed (42). Dengan 100.276 data validasi, selisih kurang dari sekitar 0,3 poin belum bisa dianggap berbeda, misalnya antara learning rate 1e-5 dan 2e-5. Selisih RoBERTa dan DistilBERT (1,5 sampai 2,2 poin) jauh lebih besar dari itu, tetapi tetap perlu dipastikan dengan seed lain.

## 5. Kesimpulan

1. Seluruh 24 run selesai dengan data penuh dalam sekitar 36 jam.
2. RoBERTa paling baik dengan learning rate 1e-5 atau 2e-5. Learning rate 5e-5 terlalu besar dan membuat training tidak stabil. DistilBERT hampir tidak terpengaruh learning rate.
3. Hasil terbaik adalah RoBERTa dengan early fusion (accuracy 0,7962, precision 0,7850, recall 0,8087, F1 0,7967).
4. DistilBERT sekitar 2 kali lebih cepat dan hemat memori, dengan performa 1,5 sampai 2,2 poin lebih rendah dari RoBERTa.
5. Konteks parent membantu, dan early fusion adalah cara penggabungan terbaik karena hasilnya setara atau lebih baik dari late fusion dengan biaya yang jauh lebih kecil.

Langkah berikutnya:
- menjalankan seed 43 dan 44 untuk konfigurasi terbaik setiap input dan model, supaya hasilnya bisa dilaporkan sebagai rata-rata dari 3 seed,
- menjalankan percobaan jumlah layer yang dilatih (early fusion),
- membuka data test untuk konfigurasi final.